# pyKVFinder results

[FILES]
INPUT = "/mnt/bkup/Ssal-KRED_orthologs/HomoLogic_Ssal-KRED_homologs_SwissProt/08_homolog_bindingsites_superposed/A0A059TC02_superposed_bindingsite_refined.pdb"
OUTPUT = "/mnt/bkup/Ssal-KRED_orthologs/HomoLogic_Ssal-KRED_homologs_SwissProt/11_detected_cavities/A0A059TC02_cavities.pdb"

[PARAMETERS]
STEP = 0.6

[RESULTS.VOLUME]
KAA = 268.92

[RESULTS.AREA]
KAA = 198.73

[RESULTS.MAX_DEPTH]
KAA = 3.98

[RESULTS.AVG_DEPTH]
KAA = 1.28

[RESULTS.AVG_HYDROPATHY]
KAA = -0.39
EisenbergWeiss = [ -1.42, 2.6,]

[RESULTS.RESIDUES]
KAA = [ [ "17", "A", "PHE",], [ "18", "A", "ILE",], [ "19", "A", "ALA",], [ "84", "A", "THR",], [ "86", "A", "SER",], [ "88", "A", "VAL",], [ "121", "A", "THR",], [ "123", "A", "SER",], [ "124", "A", "ILE",], [ "157", "A", "TYR",], [ "161", "A", "LYS",], [ "184", "A", "PRO",], [ "186", "A", "LEU",], [ "187", "A", "VAL",], [ "197", "A", "ASN",], [ "199", "A", "SER",], [ "219", "A", "GLN",],]

[RESULTS.FREQUENCY.KAA.RESIDUES]
ALA = 1
ASN = 1
GLN = 1
ILE = 2
LEU = 1
LYS = 1
PHE = 1
PRO = 1
SER = 3
THR = 2
TYR = 1
VAL = 2

[RESULTS.FREQUENCY.KAA.CLASS]
R1 = 7
R2 = 2
R3 = 7
R4 = 0
R5 = 1
RX = 0
