# pyKVFinder results

[FILES]
INPUT = "/mnt/bkup/Ssal-KRED_orthologs/HomoLogic_Ssal-KRED_homologs_SwissProt/08_homolog_bindingsites_superposed/A0A0D1BUI1_superposed_bindingsite_refined.pdb"
OUTPUT = "/mnt/bkup/Ssal-KRED_orthologs/HomoLogic_Ssal-KRED_homologs_SwissProt/11_detected_cavities/A0A0D1BUI1_cavities.pdb"

[PARAMETERS]
STEP = 0.6

[RESULTS.VOLUME]
KAA = 352.94

[RESULTS.AREA]
KAA = 244.52

[RESULTS.MAX_DEPTH]
KAA = 3.6

[RESULTS.AVG_DEPTH]
KAA = 1.25

[RESULTS.AVG_HYDROPATHY]
KAA = -0.5
EisenbergWeiss = [ -1.42, 2.6,]

[RESULTS.RESIDUES]
KAA = [ [ "18", "A", "PHE",], [ "19", "A", "VAL",], [ "83", "A", "VAL",], [ "85", "A", "SER",], [ "87", "A", "VAL",], [ "88", "A", "PRO",], [ "123", "A", "THR",], [ "125", "A", "SER",], [ "126", "A", "MET",], [ "127", "A", "SER",], [ "153", "A", "MET",], [ "156", "A", "TYR",], [ "160", "A", "LYS",], [ "183", "A", "PRO",], [ "184", "A", "VAL",], [ "185", "A", "TYR",], [ "186", "A", "ILE",], [ "200", "A", "SER",], [ "202", "A", "SER",],]

[RESULTS.FREQUENCY.KAA.RESIDUES]
ILE = 1
LYS = 1
MET = 2
PHE = 1
PRO = 2
SER = 5
THR = 1
TYR = 2
VAL = 4

[RESULTS.FREQUENCY.KAA.CLASS]
R1 = 7
R2 = 3
R3 = 8
R4 = 0
R5 = 1
RX = 0
