# pyKVFinder results

[FILES]
INPUT = "/mnt/bkup/Ssal-KRED_orthologs/HomoLogic_Ssal-KRED_homologs_SwissProt/08_homolog_bindingsites_superposed/A0A2I1BT56_superposed_bindingsite_refined.pdb"
OUTPUT = "/mnt/bkup/Ssal-KRED_orthologs/HomoLogic_Ssal-KRED_homologs_SwissProt/11_detected_cavities/A0A2I1BT56_cavities.pdb"

[PARAMETERS]
STEP = 0.6

[RESULTS.VOLUME]
KAA = 728.14

[RESULTS.AREA]
KAA = 484.26

[RESULTS.MAX_DEPTH]
KAA = 6.24

[RESULTS.AVG_DEPTH]
KAA = 2.44

[RESULTS.AVG_HYDROPATHY]
KAA = -0.12
EisenbergWeiss = [ -1.42, 2.6,]

[RESULTS.RESIDUES]
KAA = [ [ "20", "A", "ASN",], [ "22", "A", "TYR",], [ "23", "A", "LEU",], [ "24", "A", "ALA",], [ "41", "A", "THR",], [ "42", "A", "VAL",], [ "43", "A", "ARG",], [ "46", "A", "LYS",], [ "70", "A", "PHE",], [ "89", "A", "VAL",], [ "90", "A", "ALA",], [ "91", "A", "HIS",], [ "93", "A", "MET",], [ "95", "A", "TRP",], [ "129", "A", "THR",], [ "131", "A", "THR",], [ "132", "A", "ILE",], [ "174", "A", "TYR",], [ "177", "A", "HIS",], [ "181", "A", "LYS",], [ "206", "A", "PRO",], [ "208", "A", "PHE",], [ "209", "A", "SER",], [ "218", "A", "ILE",], [ "221", "A", "GLN",], [ "222", "A", "SER",], [ "224", "A", "ARG",], [ "237", "A", "MET",], [ "241", "A", "VAL",], [ "242", "A", "PRO",],]

[RESULTS.FREQUENCY.KAA.RESIDUES]
ALA = 2
ARG = 2
ASN = 1
GLN = 1
HIS = 2
ILE = 2
LEU = 1
LYS = 2
MET = 2
PHE = 2
PRO = 2
SER = 2
THR = 3
TRP = 1
TYR = 2
VAL = 3

[RESULTS.FREQUENCY.KAA.CLASS]
R1 = 10
R2 = 5
R3 = 9
R4 = 0
R5 = 6
RX = 0
