# pyKVFinder results

[FILES]
INPUT = "/mnt/bkup/Ssal-KRED_orthologs/HomoLogic_Ssal-KRED_homologs_SwissProt/08_homolog_bindingsites_superposed/A0A3G9HN61_superposed_bindingsite_refined.pdb"
OUTPUT = "/mnt/bkup/Ssal-KRED_orthologs/HomoLogic_Ssal-KRED_homologs_SwissProt/11_detected_cavities/A0A3G9HN61_cavities.pdb"

[PARAMETERS]
STEP = 0.6

[RESULTS.VOLUME]
KAA = 691.85

[RESULTS.AREA]
KAA = 433.3

[RESULTS.MAX_DEPTH]
KAA = 5.91

[RESULTS.AVG_DEPTH]
KAA = 1.65

[RESULTS.AVG_HYDROPATHY]
KAA = -0.11
EisenbergWeiss = [ -1.42, 2.6,]

[RESULTS.RESIDUES]
KAA = [ [ "11", "A", "THR",], [ "14", "A", "THR",], [ "16", "A", "HIS",], [ "17", "A", "VAL",], [ "36", "A", "LEU",], [ "37", "A", "ARG",], [ "41", "A", "LYS",], [ "70", "A", "ASP",], [ "71", "A", "MET",], [ "72", "A", "THR",], [ "90", "A", "CYS",], [ "91", "A", "ALA",], [ "92", "A", "SER",], [ "93", "A", "PRO",], [ "94", "A", "ILE",], [ "95", "A", "ASN",], [ "96", "A", "ARG",], [ "109", "A", "PRO",], [ "133", "A", "THR",], [ "135", "A", "SER",], [ "136", "A", "ASN",], [ "174", "A", "TYR",], [ "178", "A", "LYS",], [ "204", "A", "PRO",], [ "206", "A", "PHE",], [ "207", "A", "VAL",], [ "211", "A", "LYS",], [ "224", "A", "SER",],]

[RESULTS.FREQUENCY.KAA.RESIDUES]
ALA = 1
ARG = 2
ASN = 2
ASP = 1
CYS = 1
HIS = 1
ILE = 1
LEU = 1
LYS = 3
MET = 1
PHE = 1
PRO = 3
SER = 3
THR = 4
TYR = 1
VAL = 2

[RESULTS.FREQUENCY.KAA.CLASS]
R1 = 8
R2 = 2
R3 = 11
R4 = 1
R5 = 6
RX = 0
