# pyKVFinder results

[FILES]
INPUT = "/mnt/bkup/Ssal-KRED_orthologs/HomoLogic_Ssal-KRED_homologs_SwissProt/08_homolog_bindingsites_superposed/B6HV33_superposed_bindingsite_refined.pdb"
OUTPUT = "/mnt/bkup/Ssal-KRED_orthologs/HomoLogic_Ssal-KRED_homologs_SwissProt/11_detected_cavities/B6HV33_cavities.pdb"

[PARAMETERS]
STEP = 0.6

[RESULTS.VOLUME]
KAA = 241.7

[RESULTS.AREA]
KAA = 190.83

[RESULTS.MAX_DEPTH]
KAA = 3.06

[RESULTS.AVG_DEPTH]
KAA = 0.91

[RESULTS.AVG_HYDROPATHY]
KAA = -0.31
EisenbergWeiss = [ -1.42, 2.6,]

[RESULTS.RESIDUES]
KAA = [ [ "23", "A", "TYR",], [ "24", "A", "ILE",], [ "25", "A", "ALA",], [ "90", "A", "VAL",], [ "92", "A", "GLN",], [ "94", "A", "LEU",], [ "133", "A", "THR",], [ "135", "A", "SER",], [ "136", "A", "ILE",], [ "137", "A", "VAL",], [ "171", "A", "TYR",], [ "175", "A", "LYS",], [ "200", "A", "PRO",], [ "201", "A", "TRP",], [ "202", "A", "LEU",], [ "203", "A", "THR",], [ "215", "A", "SER",], [ "216", "A", "THR",], [ "234", "A", "LEU",],]

[RESULTS.FREQUENCY.KAA.RESIDUES]
ALA = 1
GLN = 1
ILE = 2
LEU = 3
LYS = 1
PRO = 1
SER = 2
THR = 3
TRP = 1
TYR = 2
VAL = 2

[RESULTS.FREQUENCY.KAA.CLASS]
R1 = 9
R2 = 3
R3 = 6
R4 = 0
R5 = 1
RX = 0
