# pyKVFinder results

[FILES]
INPUT = "/mnt/bkup/Ssal-KRED_orthologs/HomoLogic_Ssal-KRED_homologs_SwissProt/08_homolog_bindingsites_superposed/I3PLR3_superposed_bindingsite_refined.pdb"
OUTPUT = "/mnt/bkup/Ssal-KRED_orthologs/HomoLogic_Ssal-KRED_homologs_SwissProt/11_detected_cavities/I3PLR3_cavities.pdb"

[PARAMETERS]
STEP = 0.6

[RESULTS.VOLUME]
KAA = 897.7

[RESULTS.AREA]
KAA = 529.79

[RESULTS.MAX_DEPTH]
KAA = 6.29

[RESULTS.AVG_DEPTH]
KAA = 1.92

[RESULTS.AVG_HYDROPATHY]
KAA = 0.04
EisenbergWeiss = [ -1.42, 2.6,]

[RESULTS.RESIDUES]
KAA = [ [ "30", "A", "ALA",], [ "32", "A", "TYR",], [ "33", "A", "LEU",], [ "34", "A", "ALA",], [ "52", "A", "VAL",], [ "53", "A", "ARG",], [ "58", "A", "PHE",], [ "60", "A", "GLU",], [ "81", "A", "ASP",], [ "82", "A", "LEU",], [ "83", "A", "GLU",], [ "101", "A", "VAL",], [ "102", "A", "ALA",], [ "103", "A", "GLN",], [ "106", "A", "ASN",], [ "107", "A", "PHE",], [ "119", "A", "THR",], [ "143", "A", "THR",], [ "145", "A", "SER",], [ "147", "A", "ASP",], [ "186", "A", "TYR",], [ "190", "A", "LYS",], [ "213", "A", "PRO",], [ "215", "A", "LEU",], [ "216", "A", "VAL",], [ "226", "A", "PRO",], [ "227", "A", "PRO",], [ "228", "A", "SER",], [ "246", "A", "VAL",],]

[RESULTS.FREQUENCY.KAA.RESIDUES]
ALA = 3
ARG = 1
ASN = 1
ASP = 2
GLN = 1
GLU = 2
LEU = 3
LYS = 1
PHE = 2
PRO = 3
SER = 2
THR = 2
TYR = 2
VAL = 4

[RESULTS.FREQUENCY.KAA.CLASS]
R1 = 13
R2 = 4
R3 = 6
R4 = 4
R5 = 2
RX = 0
