# pyKVFinder results

[FILES]
INPUT = "/mnt/bkup/Ssal-KRED_orthologs/HomoLogic_Ssal-KRED_homologs_SwissProt/08_homolog_bindingsites_superposed/O22133_superposed_bindingsite_refined.pdb"
OUTPUT = "/mnt/bkup/Ssal-KRED_orthologs/HomoLogic_Ssal-KRED_homologs_SwissProt/11_detected_cavities/O22133_cavities.pdb"

[PARAMETERS]
STEP = 0.6

[RESULTS.VOLUME]
KAA = 892.3

[RESULTS.AREA]
KAA = 579.09

[RESULTS.MAX_DEPTH]
KAA = 8.44

[RESULTS.AVG_DEPTH]
KAA = 2.83

[RESULTS.AVG_HYDROPATHY]
KAA = -0.06
EisenbergWeiss = [ -1.42, 2.6,]

[RESULTS.RESIDUES]
KAA = [ [ "46", "A", "SER",], [ "48", "A", "PHE",], [ "49", "A", "VAL",], [ "50", "A", "ALA",], [ "67", "A", "THR",], [ "68", "A", "VAL",], [ "69", "A", "ARG",], [ "77", "A", "LYS",], [ "97", "A", "ALA",], [ "98", "A", "ASP",], [ "99", "A", "LEU",], [ "105", "A", "PHE",], [ "118", "A", "VAL",], [ "119", "A", "ALA",], [ "120", "A", "HIS",], [ "121", "A", "PRO",], [ "122", "A", "MET",], [ "123", "A", "ASP",], [ "128", "A", "GLU",], [ "136", "A", "ARG",], [ "160", "A", "THR",], [ "162", "A", "SER",], [ "198", "A", "VAL",], [ "202", "A", "TYR",], [ "206", "A", "LYS",], [ "229", "A", "ILE",], [ "231", "A", "LEU",], [ "232", "A", "VAL",], [ "238", "A", "SER",], [ "240", "A", "SER",], [ "242", "A", "PRO",], [ "243", "A", "SER",], [ "244", "A", "SER",], [ "247", "A", "ILE",],]

[RESULTS.FREQUENCY.KAA.RESIDUES]
ALA = 3
ARG = 2
ASP = 2
GLU = 1
HIS = 1
ILE = 2
LEU = 2
LYS = 2
MET = 1
PHE = 2
PRO = 2
SER = 6
THR = 2
TYR = 1
VAL = 5

[RESULTS.FREQUENCY.KAA.CLASS]
R1 = 14
R2 = 3
R3 = 9
R4 = 3
R5 = 5
RX = 0
