# pyKVFinder results

[FILES]
INPUT = "/mnt/bkup/Ssal-KRED_orthologs/HomoLogic_Ssal-KRED_homologs_SwissProt/08_homolog_bindingsites_superposed/P14721_superposed_bindingsite_refined.pdb"
OUTPUT = "/mnt/bkup/Ssal-KRED_orthologs/HomoLogic_Ssal-KRED_homologs_SwissProt/11_detected_cavities/P14721_cavities.pdb"

[PARAMETERS]
STEP = 0.6

[RESULTS.VOLUME]
KAA = 996.19

[RESULTS.AREA]
KAA = 615.15

[RESULTS.MAX_DEPTH]
KAA = 8.44

[RESULTS.AVG_DEPTH]
KAA = 2.64

[RESULTS.AVG_HYDROPATHY]
KAA = -0.03
EisenbergWeiss = [ -1.42, 2.6,]

[RESULTS.RESIDUES]
KAA = [ [ "23", "A", "THR",], [ "26", "A", "ALA",], [ "28", "A", "PHE",], [ "29", "A", "ILE",], [ "47", "A", "THR",], [ "48", "A", "VAL",], [ "49", "A", "ARG",], [ "50", "A", "ASP",], [ "56", "A", "LYS",], [ "76", "A", "ASP",], [ "77", "A", "MET",], [ "78", "A", "THR",], [ "96", "A", "LEU",], [ "97", "A", "ALA",], [ "98", "A", "THR",], [ "99", "A", "SER",], [ "100", "A", "MET",], [ "101", "A", "GLU",], [ "102", "A", "PHE",], [ "114", "A", "PRO",], [ "138", "A", "THR",], [ "140", "A", "SER",], [ "175", "A", "TYR",], [ "176", "A", "PHE",], [ "179", "A", "LYS",], [ "202", "A", "PRO",], [ "204", "A", "LEU",], [ "205", "A", "VAL",], [ "211", "A", "MET",], [ "215", "A", "PRO",], [ "216", "A", "PRO",], [ "217", "A", "SER",], [ "373", "A", "GLU",], [ "374", "A", "LYS",], [ "377", "A", "ASN",], [ "381", "A", "ASN",],]

[RESULTS.FREQUENCY.KAA.RESIDUES]
ALA = 2
ARG = 1
ASN = 2
ASP = 2
GLU = 2
ILE = 1
LEU = 2
LYS = 3
MET = 3
PHE = 3
PRO = 4
SER = 3
THR = 5
TYR = 1
VAL = 2

[RESULTS.FREQUENCY.KAA.CLASS]
R1 = 11
R2 = 4
R3 = 13
R4 = 4
R5 = 4
RX = 0
