# pyKVFinder results

[FILES]
INPUT = "/mnt/bkup/peter_ccfour/Documents/KRED_Niklaus/00_mmseqs2_database/KP104_homologs_SwissProt/08_homolog_bindingsites_superposed/P51106_superposed_bindingsite_refined.pdb"
OUTPUT = "/mnt/bkup/peter_ccfour/Documents/KRED_Niklaus/00_mmseqs2_database/KP104_homologs_SwissProt/11_detected_cavities/P51106_cavities.pdb"

[PARAMETERS]
STEP = 0.6

[RESULTS.VOLUME]
KAA = 660.74

[RESULTS.AREA]
KAA = 467.84

[RESULTS.MAX_DEPTH]
KAA = 7.8

[RESULTS.AVG_DEPTH]
KAA = 2.22

[RESULTS.AVG_HYDROPATHY]
KAA = -0.22
EisenbergWeiss = [ -1.42, 2.6,]

[RESULTS.RESIDUES]
KAA = [ [ "11", "A", "THR",], [ "14", "A", "SER",], [ "16", "A", "PHE",], [ "17", "A", "VAL",], [ "35", "A", "THR",], [ "36", "A", "VAL",], [ "37", "A", "ARG",], [ "38", "A", "ASP",], [ "44", "A", "LYS",], [ "63", "A", "ALA",], [ "64", "A", "ASP",], [ "65", "A", "LEU",], [ "66", "A", "SER",], [ "84", "A", "VAL",], [ "85", "A", "ALA",], [ "86", "A", "THR",], [ "87", "A", "PRO",], [ "88", "A", "MET",], [ "90", "A", "PHE",], [ "102", "A", "PRO",], [ "126", "A", "THR",], [ "128", "A", "SER",], [ "163", "A", "TYR",], [ "167", "A", "LYS",], [ "190", "A", "PRO",], [ "192", "A", "LEU",], [ "193", "A", "VAL",], [ "203", "A", "PRO",], [ "204", "A", "PRO",], [ "205", "A", "SER",], [ "208", "A", "THR",], [ "234", "A", "LEU",],]

[RESULTS.FREQUENCY.KAA.RESIDUES]
ALA = 2
ARG = 1
ASP = 2
LEU = 3
LYS = 2
MET = 1
PHE = 2
PRO = 5
SER = 4
THR = 5
TYR = 1
VAL = 4

[RESULTS.FREQUENCY.KAA.CLASS]
R1 = 14
R2 = 3
R3 = 10
R4 = 2
R5 = 3
RX = 0
