# pyKVFinder results

[FILES]
INPUT = "/mnt/bkup/Ssal-KRED_orthologs/HomoLogic_Ssal-KRED_homologs_SwissProt/08_homolog_bindingsites_superposed/P51105_superposed_bindingsite_refined.pdb"
OUTPUT = "/mnt/bkup/Ssal-KRED_orthologs/HomoLogic_Ssal-KRED_homologs_SwissProt/11_detected_cavities/P51105_cavities.pdb"

[PARAMETERS]
STEP = 0.6

[RESULTS.VOLUME]
KAA = 711.5

[RESULTS.AREA]
KAA = 439.42

[RESULTS.MAX_DEPTH]
KAA = 7.32

[RESULTS.AVG_DEPTH]
KAA = 2.08

[RESULTS.AVG_HYDROPATHY]
KAA = -0.19
EisenbergWeiss = [ -1.42, 2.6,]

[RESULTS.RESIDUES]
KAA = [ [ "15", "A", "ALA",], [ "17", "A", "PHE",], [ "18", "A", "ILE",], [ "37", "A", "VAL",], [ "38", "A", "ARG",], [ "39", "A", "ASP",], [ "45", "A", "LYS",], [ "65", "A", "ASP",], [ "66", "A", "LEU",], [ "67", "A", "THR",], [ "85", "A", "LEU",], [ "86", "A", "ALA",], [ "87", "A", "THR",], [ "88", "A", "PRO",], [ "89", "A", "MET",], [ "103", "A", "PRO",], [ "127", "A", "THR",], [ "129", "A", "SER",], [ "164", "A", "TYR",], [ "168", "A", "LYS",], [ "191", "A", "PRO",], [ "194", "A", "VAL",], [ "205", "A", "PRO",], [ "206", "A", "SER",], [ "356", "A", "LYS",], [ "360", "A", "CYS",],]

[RESULTS.FREQUENCY.KAA.RESIDUES]
ALA = 2
ARG = 1
ASP = 2
CYS = 1
ILE = 1
LEU = 2
LYS = 3
MET = 1
PHE = 1
PRO = 4
SER = 2
THR = 3
TYR = 1
VAL = 2

[RESULTS.FREQUENCY.KAA.CLASS]
R1 = 11
R2 = 2
R3 = 7
R4 = 2
R5 = 4
RX = 0
