# pyKVFinder results

[FILES]
INPUT = "/mnt/bkup/Ssal-KRED_orthologs/HomoLogic_Ssal-KRED_homologs_SwissProt/08_homolog_bindingsites_superposed/P51103_superposed_bindingsite_refined.pdb"
OUTPUT = "/mnt/bkup/Ssal-KRED_orthologs/HomoLogic_Ssal-KRED_homologs_SwissProt/11_detected_cavities/P51103_cavities.pdb"

[PARAMETERS]
STEP = 0.6

[RESULTS.VOLUME]
KAA = 668.74

[RESULTS.AREA]
KAA = 431.59

[RESULTS.MAX_DEPTH]
KAA = 9.08

[RESULTS.AVG_DEPTH]
KAA = 2.89

[RESULTS.AVG_HYDROPATHY]
KAA = -0.33
EisenbergWeiss = [ -1.42, 2.6,]

[RESULTS.RESIDUES]
KAA = [ [ "15", "A", "ALA",], [ "17", "A", "PHE",], [ "18", "A", "ILE",], [ "37", "A", "VAL",], [ "38", "A", "ARG",], [ "39", "A", "ASN",], [ "45", "A", "LYS",], [ "65", "A", "ASP",], [ "66", "A", "LEU",], [ "67", "A", "THR",], [ "85", "A", "VAL",], [ "86", "A", "ALA",], [ "87", "A", "THR",], [ "88", "A", "PRO",], [ "89", "A", "MET",], [ "103", "A", "PRO",], [ "127", "A", "THR",], [ "129", "A", "SER",], [ "164", "A", "TYR",], [ "168", "A", "LYS",], [ "191", "A", "PRO",], [ "193", "A", "LEU",], [ "194", "A", "VAL",], [ "200", "A", "ASN",], [ "204", "A", "PRO",], [ "205", "A", "PRO",], [ "206", "A", "SER",], [ "362", "A", "LEU",],]

[RESULTS.FREQUENCY.KAA.RESIDUES]
ALA = 2
ARG = 1
ASN = 2
ASP = 1
ILE = 1
LEU = 3
LYS = 2
MET = 1
PHE = 1
PRO = 5
SER = 2
THR = 3
TYR = 1
VAL = 3

[RESULTS.FREQUENCY.KAA.CLASS]
R1 = 14
R2 = 2
R3 = 8
R4 = 1
R5 = 3
RX = 0
