# pyKVFinder results

[FILES]
INPUT = "/mnt/bkup/Ssal-KRED_orthologs/HomoLogic_Ssal-KRED_homologs_SwissProt/08_homolog_bindingsites_superposed/P53183_superposed_bindingsite_refined.pdb"
OUTPUT = "/mnt/bkup/Ssal-KRED_orthologs/HomoLogic_Ssal-KRED_homologs_SwissProt/11_detected_cavities/P53183_cavities.pdb"

[PARAMETERS]
STEP = 0.6

[RESULTS.VOLUME]
KAA = 142.13
KAB = 314.28

[RESULTS.AREA]
KAA = 118.47
KAB = 237.37

[RESULTS.MAX_DEPTH]
KAA = 2.4
KAB = 3.89

[RESULTS.AVG_DEPTH]
KAA = 0.75
KAB = 1.28

[RESULTS.AVG_HYDROPATHY]
KAA = 0.33
KAB = -0.49
EisenbergWeiss = [ -1.42, 2.6,]

[RESULTS.RESIDUES]
KAA = [ [ "14", "A", "THR",], [ "35", "A", "SER",], [ "37", "A", "ARG",], [ "41", "A", "LYS",], [ "60", "A", "VAL",], [ "62", "A", "ASP",], [ "63", "A", "ILE",], [ "87", "A", "ALA",], [ "89", "A", "PRO",], [ "104", "A", "PRO",],]
KAB = [ [ "16", "A", "PHE",], [ "17", "A", "ILE",], [ "18", "A", "ALA",], [ "86", "A", "ILE",], [ "87", "A", "ALA",], [ "88", "A", "SER",], [ "90", "A", "VAL",], [ "92", "A", "PHE",], [ "130", "A", "THR",], [ "132", "A", "SER",], [ "170", "A", "TYR",], [ "174", "A", "LYS",], [ "201", "A", "PRO",], [ "203", "A", "PHE",], [ "204", "A", "VAL",], [ "219", "A", "ASN",], [ "220", "A", "SER",], [ "221", "A", "SER",],]

[RESULTS.FREQUENCY.KAA.RESIDUES]
ALA = 1
ARG = 1
ASP = 1
ILE = 1
LYS = 1
PRO = 2
SER = 1
THR = 1
VAL = 1

[RESULTS.FREQUENCY.KAA.CLASS]
R1 = 5
R2 = 0
R3 = 2
R4 = 1
R5 = 2
RX = 0

[RESULTS.FREQUENCY.KAB.RESIDUES]
ALA = 2
ASN = 1
ILE = 2
LYS = 1
PHE = 3
PRO = 1
SER = 4
THR = 1
TYR = 1
VAL = 2

[RESULTS.FREQUENCY.KAB.CLASS]
R1 = 7
R2 = 4
R3 = 6
R4 = 0
R5 = 1
RX = 0
