# pyKVFinder results

[FILES]
INPUT = "/mnt/bkup/Ssal-KRED_orthologs/HomoLogic_Ssal-KRED_homologs_SwissProt/08_homolog_bindingsites_superposed/Q6K9A2_superposed_bindingsite_refined.pdb"
OUTPUT = "/mnt/bkup/Ssal-KRED_orthologs/HomoLogic_Ssal-KRED_homologs_SwissProt/11_detected_cavities/Q6K9A2_cavities.pdb"

[PARAMETERS]
STEP = 0.6

[RESULTS.VOLUME]
KAA = 302.4

[RESULTS.AREA]
KAA = 228.24

[RESULTS.MAX_DEPTH]
KAA = 3.89

[RESULTS.AVG_DEPTH]
KAA = 1.32

[RESULTS.AVG_HYDROPATHY]
KAA = -0.4
EisenbergWeiss = [ -1.42, 2.6,]

[RESULTS.RESIDUES]
KAA = [ [ "26", "A", "PHE",], [ "27", "A", "ILE",], [ "93", "A", "VAL",], [ "95", "A", "SER",], [ "97", "A", "VAL",], [ "129", "A", "THR",], [ "131", "A", "SER",], [ "132", "A", "TYR",], [ "165", "A", "TYR",], [ "169", "A", "LYS",], [ "192", "A", "PRO",], [ "194", "A", "MET",], [ "195", "A", "THR",], [ "205", "A", "ASN",], [ "206", "A", "PHE",], [ "207", "A", "SER",],]

[RESULTS.FREQUENCY.KAA.RESIDUES]
ASN = 1
ILE = 1
LYS = 1
MET = 1
PHE = 2
PRO = 1
SER = 3
THR = 2
TYR = 2
VAL = 2

[RESULTS.FREQUENCY.KAA.CLASS]
R1 = 4
R2 = 4
R3 = 7
R4 = 0
R5 = 1
RX = 0
