# pyKVFinder results

[FILES]
INPUT = "/mnt/bkup/Ssal-KRED_orthologs/HomoLogic_Ssal-KRED_homologs_SwissProt/08_homolog_bindingsites_superposed/Q9CA28_superposed_bindingsite_refined.pdb"
OUTPUT = "/mnt/bkup/Ssal-KRED_orthologs/HomoLogic_Ssal-KRED_homologs_SwissProt/11_detected_cavities/Q9CA28_cavities.pdb"

[PARAMETERS]
STEP = 0.6

[RESULTS.VOLUME]
KAA = 633.31

[RESULTS.AREA]
KAA = 441.32

[RESULTS.MAX_DEPTH]
KAA = 6.63

[RESULTS.AVG_DEPTH]
KAA = 2.09

[RESULTS.AVG_HYDROPATHY]
KAA = -0.21
EisenbergWeiss = [ -1.42, 2.6,]

[RESULTS.RESIDUES]
KAA = [ [ "10", "A", "THR",], [ "12", "A", "PHE",], [ "13", "A", "ILE",], [ "14", "A", "ALA",], [ "32", "A", "VAL",], [ "33", "A", "ARG",], [ "34", "A", "ASN",], [ "40", "A", "LYS",], [ "60", "A", "ASP",], [ "61", "A", "LEU",], [ "62", "A", "THR",], [ "80", "A", "THR",], [ "81", "A", "ALA",], [ "82", "A", "SER",], [ "83", "A", "PRO",], [ "84", "A", "VAL",], [ "85", "A", "LEU",], [ "99", "A", "PRO",], [ "124", "A", "THR",], [ "126", "A", "SER",], [ "127", "A", "CYS",], [ "128", "A", "SER",], [ "160", "A", "TYR",], [ "164", "A", "LYS",], [ "187", "A", "PRO",], [ "188", "A", "SER",], [ "189", "A", "PHE",], [ "190", "A", "VAL",], [ "200", "A", "THR",], [ "201", "A", "SER",], [ "202", "A", "THR",],]

[RESULTS.FREQUENCY.KAA.RESIDUES]
ALA = 2
ARG = 1
ASN = 1
ASP = 1
CYS = 1
ILE = 1
LEU = 2
LYS = 2
PHE = 2
PRO = 3
SER = 5
THR = 6
TYR = 1
VAL = 3

[RESULTS.FREQUENCY.KAA.CLASS]
R1 = 11
R2 = 3
R3 = 13
R4 = 1
R5 = 3
RX = 0
