# pyKVFinder results

[FILES]
INPUT = "/mnt/bkup/peter_ccfour/Documents/KRED_Niklaus/00_mmseqs2_database/KP104_homologs_SwissProt/08_homolog_bindingsites_superposed/Q9Y7K4_superposed_bindingsite_refined.pdb"
OUTPUT = "/mnt/bkup/peter_ccfour/Documents/KRED_Niklaus/00_mmseqs2_database/KP104_homologs_SwissProt/11_detected_cavities/Q9Y7K4_cavities.pdb"

[PARAMETERS]
STEP = 0.6

[RESULTS.VOLUME]
KAA = 663.77

[RESULTS.AREA]
KAA = 417.03

[RESULTS.MAX_DEPTH]
KAA = 6.92

[RESULTS.AVG_DEPTH]
KAA = 1.65

[RESULTS.AVG_HYDROPATHY]
KAA = -0.3
EisenbergWeiss = [ -1.42, 2.6,]

[RESULTS.RESIDUES]
KAA = [ [ "9", "A", "ALA",], [ "11", "A", "PHE",], [ "12", "A", "ILE",], [ "30", "A", "LEU",], [ "31", "A", "VAL",], [ "32", "A", "ARG",], [ "36", "A", "ASN",], [ "51", "A", "THR",], [ "52", "A", "LEU",], [ "53", "A", "GLU",], [ "70", "A", "HIS",], [ "71", "A", "THR",], [ "72", "A", "ALA",], [ "73", "A", "PHE",], [ "74", "A", "VAL",], [ "75", "A", "HIS",], [ "87", "A", "ASP",], [ "108", "A", "THR",], [ "110", "A", "VAL",], [ "134", "A", "ARG",], [ "156", "A", "LEU",], [ "159", "A", "THR",], [ "160", "A", "VAL",], [ "166", "A", "HIS",], [ "168", "A", "PHE",],]

[RESULTS.FREQUENCY.KAA.RESIDUES]
ALA = 2
ARG = 2
ASN = 1
ASP = 1
GLU = 1
HIS = 3
ILE = 1
LEU = 3
PHE = 3
THR = 4
VAL = 4

[RESULTS.FREQUENCY.KAA.CLASS]
R1 = 10
R2 = 3
R3 = 5
R4 = 2
R5 = 5
RX = 0
