# pyKVFinder results

[FILES]
INPUT = "/mnt/bkup/Ssal-KRED_orthologs/HomoLogic_Ort-RDM_1_3_homologs_tested/08_homolog_bindingsites_superposed/ABN65471_superposed_bindingsite_refined.pdb"
OUTPUT = "/mnt/bkup/Ssal-KRED_orthologs/HomoLogic_Ort-RDM_1_3_homologs_tested/11_detected_cavities/ABN65471_cavities.pdb"

[PARAMETERS]
STEP = 0.6

[RESULTS.VOLUME]
KAA = 102.38
KAB = 311.69

[RESULTS.AREA]
KAA = 91.99
KAB = 241.88

[RESULTS.MAX_DEPTH]
KAA = 2.16
KAB = 3.23

[RESULTS.AVG_DEPTH]
KAA = 0.75
KAB = 1.21

[RESULTS.AVG_HYDROPATHY]
KAA = 0.15
KAB = -0.35
EisenbergWeiss = [ -1.42, 2.6,]

[RESULTS.RESIDUES]
KAA = [ [ "11", "A", "SER",], [ "32", "A", "SER",], [ "33", "A", "VAL",], [ "34", "A", "ARG",], [ "56", "A", "VAL",], [ "59", "A", "ILE",], [ "82", "A", "ALA",], [ "84", "A", "PRO",], [ "99", "A", "PRO",],]
KAB = [ [ "13", "A", "TYR",], [ "14", "A", "ILE",], [ "15", "A", "ALA",], [ "81", "A", "THR",], [ "83", "A", "SER",], [ "85", "A", "PHE",], [ "87", "A", "PHE",], [ "124", "A", "THR",], [ "126", "A", "SER",], [ "127", "A", "TYR",], [ "162", "A", "TYR",], [ "166", "A", "LYS",], [ "191", "A", "PRO",], [ "192", "A", "THR",], [ "193", "A", "TYR",], [ "194", "A", "VAL",], [ "209", "A", "SER",], [ "211", "A", "SER",],]

[RESULTS.FREQUENCY.KAA.RESIDUES]
ALA = 1
ARG = 1
ILE = 1
PRO = 2
SER = 2
VAL = 2

[RESULTS.FREQUENCY.KAA.CLASS]
R1 = 6
R2 = 0
R3 = 2
R4 = 0
R5 = 1
RX = 0

[RESULTS.FREQUENCY.KAB.RESIDUES]
ALA = 1
ILE = 1
LYS = 1
PHE = 2
PRO = 1
SER = 4
THR = 3
TYR = 4
VAL = 1

[RESULTS.FREQUENCY.KAB.CLASS]
R1 = 4
R2 = 6
R3 = 7
R4 = 0
R5 = 1
RX = 0
