# pyKVFinder results

[FILES]
INPUT = "/mnt/bkup/Ssal-KRED_orthologs/HomoLogic_Ort-RDM_1_3_homologs_tested/08_homolog_bindingsites_superposed/CCG22285_superposed_bindingsite_refined.pdb"
OUTPUT = "/mnt/bkup/Ssal-KRED_orthologs/HomoLogic_Ort-RDM_1_3_homologs_tested/11_detected_cavities/CCG22285_cavities.pdb"

[PARAMETERS]
STEP = 0.6

[RESULTS.VOLUME]
KAA = 333.29

[RESULTS.AREA]
KAA = 228.15

[RESULTS.MAX_DEPTH]
KAA = 3.79

[RESULTS.AVG_DEPTH]
KAA = 1.41

[RESULTS.AVG_HYDROPATHY]
KAA = -0.43
EisenbergWeiss = [ -1.42, 2.6,]

[RESULTS.RESIDUES]
KAA = [ [ "11", "A", "PHE",], [ "12", "A", "ILE",], [ "13", "A", "ALA",], [ "84", "A", "THR",], [ "85", "A", "ALA",], [ "86", "A", "SER",], [ "88", "A", "VAL",], [ "127", "A", "THR",], [ "129", "A", "SER",], [ "167", "A", "TYR",], [ "171", "A", "LYS",], [ "196", "A", "PRO",], [ "198", "A", "VAL",], [ "199", "A", "VAL",], [ "214", "A", "ASN",], [ "215", "A", "TYR",], [ "216", "A", "SER",],]

[RESULTS.FREQUENCY.KAA.RESIDUES]
ALA = 2
ASN = 1
ILE = 1
LYS = 1
PHE = 1
PRO = 1
SER = 3
THR = 2
TYR = 2
VAL = 3

[RESULTS.FREQUENCY.KAA.CLASS]
R1 = 7
R2 = 3
R3 = 6
R4 = 0
R5 = 1
RX = 0
