# pyKVFinder results

[FILES]
INPUT = "/mnt/bkup/Ssal-KRED_orthologs/HomoLogic_Ort-RDM_1_3_homologs_tested/08_homolog_bindingsites_superposed/CCG22283_superposed_bindingsite_refined.pdb"
OUTPUT = "/mnt/bkup/Ssal-KRED_orthologs/HomoLogic_Ort-RDM_1_3_homologs_tested/11_detected_cavities/CCG22283_cavities.pdb"

[PARAMETERS]
STEP = 0.6

[RESULTS.VOLUME]
KAA = 552.96

[RESULTS.AREA]
KAA = 413.36

[RESULTS.MAX_DEPTH]
KAA = 4.24

[RESULTS.AVG_DEPTH]
KAA = 1.44

[RESULTS.AVG_HYDROPATHY]
KAA = -0.2
EisenbergWeiss = [ -1.42, 2.6,]

[RESULTS.RESIDUES]
KAA = [ [ "6", "A", "THR",], [ "9", "A", "THR",], [ "11", "A", "TYR",], [ "12", "A", "ILE",], [ "13", "A", "ALA",], [ "30", "A", "THR",], [ "31", "A", "VAL",], [ "32", "A", "ARG",], [ "36", "A", "LYS",], [ "54", "A", "VAL",], [ "57", "A", "ILE",], [ "79", "A", "ALA",], [ "80", "A", "ALA",], [ "81", "A", "SER",], [ "82", "A", "PRO",], [ "83", "A", "VAL",], [ "85", "A", "PHE",], [ "97", "A", "PRO",], [ "121", "A", "THR",], [ "123", "A", "SER",], [ "124", "A", "THR",], [ "125", "A", "ALA",], [ "128", "A", "ARG",], [ "161", "A", "TYR",], [ "165", "A", "LYS",], [ "190", "A", "PRO",], [ "191", "A", "THR",], [ "192", "A", "PHE",], [ "193", "A", "VAL",], [ "208", "A", "ASN",], [ "209", "A", "GLU",], [ "210", "A", "SER",],]

[RESULTS.FREQUENCY.KAA.RESIDUES]
ALA = 4
ARG = 2
ASN = 1
GLU = 1
ILE = 2
LYS = 2
PHE = 2
PRO = 3
SER = 3
THR = 6
TYR = 2
VAL = 4

[RESULTS.FREQUENCY.KAA.CLASS]
R1 = 13
R2 = 4
R3 = 10
R4 = 1
R5 = 4
RX = 0
