# pyKVFinder results

[FILES]
INPUT = "/mnt/bkup/Ssal-KRED_orthologs/HomoLogic_Ort-RDM_1_3_homologs_tested/08_homolog_bindingsites_superposed/EEQ38647_superposed_bindingsite_refined.pdb"
OUTPUT = "/mnt/bkup/Ssal-KRED_orthologs/HomoLogic_Ort-RDM_1_3_homologs_tested/11_detected_cavities/EEQ38647_cavities.pdb"

[PARAMETERS]
STEP = 0.6

[RESULTS.VOLUME]
KAA = 640.66

[RESULTS.AREA]
KAA = 479.54

[RESULTS.MAX_DEPTH]
KAA = 5.66

[RESULTS.AVG_DEPTH]
KAA = 2.06

[RESULTS.AVG_HYDROPATHY]
KAA = -0.11
EisenbergWeiss = [ -1.42, 2.6,]

[RESULTS.RESIDUES]
KAA = [ [ "7", "A", "SER",], [ "10", "A", "ASN",], [ "12", "A", "PHE",], [ "13", "A", "ILE",], [ "31", "A", "SER",], [ "32", "A", "VAL",], [ "33", "A", "ARG",], [ "54", "A", "VAL",], [ "57", "A", "PHE",], [ "63", "A", "PHE",], [ "79", "A", "SER",], [ "80", "A", "ALA",], [ "81", "A", "SER",], [ "82", "A", "PRO",], [ "83", "A", "VAL",], [ "85", "A", "PHE",], [ "122", "A", "THR",], [ "124", "A", "SER",], [ "158", "A", "TYR",], [ "162", "A", "LYS",], [ "187", "A", "PRO",], [ "189", "A", "TYR",], [ "190", "A", "VAL",], [ "205", "A", "THR",], [ "206", "A", "SER",], [ "207", "A", "SER",], [ "210", "A", "TYR",],]

[RESULTS.FREQUENCY.KAA.RESIDUES]
ALA = 1
ARG = 1
ASN = 1
ILE = 1
LYS = 1
PHE = 4
PRO = 2
SER = 7
THR = 2
TYR = 3
VAL = 4

[RESULTS.FREQUENCY.KAA.CLASS]
R1 = 8
R2 = 7
R3 = 10
R4 = 0
R5 = 2
RX = 0
