# pyKVFinder results

[FILES]
INPUT = "/mnt/bkup/Ssal-KRED_orthologs/HomoLogic_Ort-RDM_1_3_homologs_tested/08_homolog_bindingsites_superposed/EER34926_superposed_bindingsite_refined.pdb"
OUTPUT = "/mnt/bkup/Ssal-KRED_orthologs/HomoLogic_Ort-RDM_1_3_homologs_tested/11_detected_cavities/EER34926_cavities.pdb"

[PARAMETERS]
STEP = 0.6

[RESULTS.VOLUME]
KAA = 476.06

[RESULTS.AREA]
KAA = 394.51

[RESULTS.MAX_DEPTH]
KAA = 3.84

[RESULTS.AVG_DEPTH]
KAA = 1.4

[RESULTS.AVG_HYDROPATHY]
KAA = -0.18
EisenbergWeiss = [ -1.42, 2.6,]

[RESULTS.RESIDUES]
KAA = [ [ "16", "A", "SER",], [ "18", "A", "TYR",], [ "19", "A", "ILE",], [ "20", "A", "ALA",], [ "37", "A", "THR",], [ "38", "A", "VAL",], [ "39", "A", "ARG",], [ "66", "A", "VAL",], [ "69", "A", "ILE",], [ "90", "A", "HIS",], [ "91", "A", "THR",], [ "92", "A", "ALA",], [ "93", "A", "SER",], [ "94", "A", "PRO",], [ "95", "A", "PHE",], [ "97", "A", "PHE",], [ "109", "A", "PRO",], [ "134", "A", "THR",], [ "136", "A", "SER",], [ "137", "A", "TYR",], [ "138", "A", "VAL",], [ "174", "A", "TYR",], [ "175", "A", "PHE",], [ "178", "A", "LYS",], [ "203", "A", "PRO",], [ "204", "A", "ALA",], [ "205", "A", "TYR",], [ "206", "A", "VAL",], [ "221", "A", "ASN",], [ "223", "A", "SER",],]

[RESULTS.FREQUENCY.KAA.RESIDUES]
ALA = 3
ARG = 1
ASN = 1
HIS = 1
ILE = 2
LYS = 1
PHE = 3
PRO = 3
SER = 4
THR = 3
TYR = 4
VAL = 4

[RESULTS.FREQUENCY.KAA.CLASS]
R1 = 12
R2 = 7
R3 = 8
R4 = 0
R5 = 3
RX = 0
