# pyKVFinder results

[FILES]
INPUT = "/mnt/bkup/Ssal-KRED_orthologs/HomoLogic_Ort-RDM_1_3_homologs_tested/08_homolog_bindingsites_superposed/EER31342_superposed_bindingsite_refined.pdb"
OUTPUT = "/mnt/bkup/Ssal-KRED_orthologs/HomoLogic_Ort-RDM_1_3_homologs_tested/11_detected_cavities/EER31342_cavities.pdb"

[PARAMETERS]
STEP = 0.6

[RESULTS.VOLUME]
KAA = 535.46

[RESULTS.AREA]
KAA = 364.09

[RESULTS.MAX_DEPTH]
KAA = 3.45

[RESULTS.AVG_DEPTH]
KAA = 1.05

[RESULTS.AVG_HYDROPATHY]
KAA = -0.25
EisenbergWeiss = [ -1.42, 2.6,]

[RESULTS.RESIDUES]
KAA = [ [ "6", "A", "THR",], [ "9", "A", "SER",], [ "11", "A", "TYR",], [ "12", "A", "VAL",], [ "31", "A", "VAL",], [ "32", "A", "ARG",], [ "57", "A", "LEU",], [ "58", "A", "ASP",], [ "79", "A", "THR",], [ "80", "A", "ALA",], [ "81", "A", "SER",], [ "82", "A", "VAL",], [ "83", "A", "VAL",], [ "85", "A", "PHE",], [ "101", "A", "ILE",], [ "122", "A", "THR",], [ "124", "A", "SER",], [ "125", "A", "SER",], [ "126", "A", "ALA",], [ "135", "A", "PHE",], [ "162", "A", "TYR",], [ "163", "A", "PHE",], [ "166", "A", "LYS",], [ "191", "A", "PRO",], [ "193", "A", "LEU",], [ "194", "A", "ILE",], [ "211", "A", "SER",], [ "212", "A", "THR",],]

[RESULTS.FREQUENCY.KAA.RESIDUES]
ALA = 2
ARG = 1
ASP = 1
ILE = 2
LEU = 2
LYS = 1
PHE = 3
PRO = 1
SER = 5
THR = 4
TYR = 2
VAL = 4

[RESULTS.FREQUENCY.KAA.CLASS]
R1 = 11
R2 = 5
R3 = 9
R4 = 1
R5 = 2
RX = 0
