# pyKVFinder results

[FILES]
INPUT = "/mnt/bkup/Ssal-KRED_orthologs/HomoLogic_Ort-RDM_1_3_homologs_tested/08_homolog_bindingsites_superposed/EGW35479_superposed_bindingsite_refined.pdb"
OUTPUT = "/mnt/bkup/Ssal-KRED_orthologs/HomoLogic_Ort-RDM_1_3_homologs_tested/11_detected_cavities/EGW35479_cavities.pdb"

[PARAMETERS]
STEP = 0.6

[RESULTS.VOLUME]
KAA = 594.0

[RESULTS.AREA]
KAA = 450.84

[RESULTS.MAX_DEPTH]
KAA = 4.53

[RESULTS.AVG_DEPTH]
KAA = 1.62

[RESULTS.AVG_HYDROPATHY]
KAA = -0.21
EisenbergWeiss = [ -1.42, 2.6,]

[RESULTS.RESIDUES]
KAA = [ [ "9", "A", "SER",], [ "12", "A", "ASN",], [ "14", "A", "TYR",], [ "15", "A", "ILE",], [ "16", "A", "ALA",], [ "33", "A", "SER",], [ "34", "A", "VAL",], [ "35", "A", "ARG",], [ "39", "A", "LYS",], [ "57", "A", "VAL",], [ "60", "A", "LEU",], [ "82", "A", "THR",], [ "83", "A", "ALA",], [ "84", "A", "SER",], [ "85", "A", "PRO",], [ "86", "A", "VAL",], [ "88", "A", "PHE",], [ "100", "A", "PRO",], [ "125", "A", "THR",], [ "127", "A", "SER",], [ "128", "A", "ALA",], [ "129", "A", "VAL",], [ "134", "A", "TRP",], [ "165", "A", "TYR",], [ "169", "A", "LYS",], [ "194", "A", "PRO",], [ "195", "A", "VAL",], [ "196", "A", "TYR",], [ "197", "A", "VAL",], [ "212", "A", "ASN",], [ "213", "A", "LEU",], [ "214", "A", "SER",], [ "235", "A", "SER",],]

[RESULTS.FREQUENCY.KAA.RESIDUES]
ALA = 3
ARG = 1
ASN = 2
ILE = 1
LEU = 2
LYS = 2
PHE = 1
PRO = 3
SER = 6
THR = 2
TRP = 1
TYR = 3
VAL = 6

[RESULTS.FREQUENCY.KAA.CLASS]
R1 = 15
R2 = 5
R3 = 10
R4 = 0
R5 = 3
RX = 0
