# pyKVFinder results

[FILES]
INPUT = "/mnt/bkup/Ssal-KRED_orthologs/HomoLogic_Ort-RDM_1_3_homologs_tested/08_homolog_bindingsites_superposed/EGW33294_superposed_bindingsite_refined.pdb"
OUTPUT = "/mnt/bkup/Ssal-KRED_orthologs/HomoLogic_Ort-RDM_1_3_homologs_tested/11_detected_cavities/EGW33294_cavities.pdb"

[PARAMETERS]
STEP = 0.6

[RESULTS.VOLUME]
KAA = 591.84

[RESULTS.AREA]
KAA = 430.3

[RESULTS.MAX_DEPTH]
KAA = 4.24

[RESULTS.AVG_DEPTH]
KAA = 1.48

[RESULTS.AVG_HYDROPATHY]
KAA = -0.19
EisenbergWeiss = [ -1.42, 2.6,]

[RESULTS.RESIDUES]
KAA = [ [ "9", "A", "SER",], [ "12", "A", "ASN",], [ "14", "A", "TYR",], [ "15", "A", "ILE",], [ "16", "A", "ALA",], [ "33", "A", "SER",], [ "35", "A", "ARG",], [ "57", "A", "ILE",], [ "60", "A", "ILE",], [ "61", "A", "SER",], [ "82", "A", "THR",], [ "83", "A", "ALA",], [ "84", "A", "SER",], [ "85", "A", "PRO",], [ "86", "A", "VAL",], [ "88", "A", "PHE",], [ "100", "A", "PRO",], [ "125", "A", "THR",], [ "127", "A", "SER",], [ "166", "A", "TYR",], [ "167", "A", "PHE",], [ "170", "A", "LYS",], [ "195", "A", "PRO",], [ "196", "A", "VAL",], [ "197", "A", "TYR",], [ "198", "A", "ASN",], [ "213", "A", "ASN",], [ "214", "A", "VAL",], [ "215", "A", "SER",], [ "236", "A", "ASN",],]

[RESULTS.FREQUENCY.KAA.RESIDUES]
ALA = 2
ARG = 1
ASN = 4
ILE = 3
LYS = 1
PHE = 2
PRO = 3
SER = 6
THR = 2
TYR = 3
VAL = 3

[RESULTS.FREQUENCY.KAA.CLASS]
R1 = 11
R2 = 5
R3 = 12
R4 = 0
R5 = 2
RX = 0
