# pyKVFinder results

[FILES]
INPUT = "/mnt/bkup/Ssal-KRED_orthologs/HomoLogic_Ort-RDM_1_3_homologs_tested/08_homolog_bindingsites_superposed/EGW35463_superposed_bindingsite_refined.pdb"
OUTPUT = "/mnt/bkup/Ssal-KRED_orthologs/HomoLogic_Ort-RDM_1_3_homologs_tested/11_detected_cavities/EGW35463_cavities.pdb"

[PARAMETERS]
STEP = 0.6

[RESULTS.VOLUME]
KAA = 113.83
KAB = 363.96

[RESULTS.AREA]
KAA = 96.19
KAB = 262.58

[RESULTS.MAX_DEPTH]
KAA = 2.47
KAB = 4.41

[RESULTS.AVG_DEPTH]
KAA = 0.79
KAB = 1.5

[RESULTS.AVG_HYDROPATHY]
KAA = 0.49
KAB = -0.41
EisenbergWeiss = [ -1.42, 2.6,]

[RESULTS.RESIDUES]
KAA = [ [ "9", "A", "SER",], [ "12", "A", "ASN",], [ "33", "A", "SER",], [ "34", "A", "VAL",], [ "35", "A", "ARG",], [ "39", "A", "LYS",], [ "57", "A", "VAL",], [ "60", "A", "LEU",], [ "83", "A", "ALA",], [ "85", "A", "PRO",], [ "100", "A", "PRO",],]
KAB = [ [ "14", "A", "PHE",], [ "15", "A", "ILE",], [ "16", "A", "ALA",], [ "82", "A", "ALA",], [ "83", "A", "ALA",], [ "84", "A", "SER",], [ "86", "A", "VAL",], [ "88", "A", "PHE",], [ "125", "A", "THR",], [ "127", "A", "SER",], [ "129", "A", "VAL",], [ "165", "A", "TYR",], [ "169", "A", "LYS",], [ "194", "A", "PRO",], [ "196", "A", "TYR",], [ "197", "A", "VAL",], [ "212", "A", "ASN",], [ "213", "A", "LEU",], [ "214", "A", "SER",],]

[RESULTS.FREQUENCY.KAA.RESIDUES]
ALA = 1
ARG = 1
ASN = 1
LEU = 1
LYS = 1
PRO = 2
SER = 2
VAL = 2

[RESULTS.FREQUENCY.KAA.CLASS]
R1 = 6
R2 = 0
R3 = 3
R4 = 0
R5 = 2
RX = 0

[RESULTS.FREQUENCY.KAB.RESIDUES]
ALA = 3
ASN = 1
ILE = 1
LEU = 1
LYS = 1
PHE = 2
PRO = 1
SER = 3
THR = 1
TYR = 2
VAL = 3

[RESULTS.FREQUENCY.KAB.CLASS]
R1 = 9
R2 = 4
R3 = 5
R4 = 0
R5 = 1
RX = 0
