# pyKVFinder results

[FILES]
INPUT = "/mnt/bkup/Ssal-KRED_orthologs/HomoLogic_Ort-RDM_1_3_homologs_tested/08_homolog_bindingsites_superposed/EMG50733_superposed_bindingsite_refined.pdb"
OUTPUT = "/mnt/bkup/Ssal-KRED_orthologs/HomoLogic_Ort-RDM_1_3_homologs_tested/11_detected_cavities/EMG50733_cavities.pdb"

[PARAMETERS]
STEP = 0.6

[RESULTS.VOLUME]
KAA = 626.62

[RESULTS.AREA]
KAA = 461.49

[RESULTS.MAX_DEPTH]
KAA = 5.02

[RESULTS.AVG_DEPTH]
KAA = 1.8

[RESULTS.AVG_HYDROPATHY]
KAA = -0.28
EisenbergWeiss = [ -1.42, 2.6,]

[RESULTS.RESIDUES]
KAA = [ [ "12", "A", "SER",], [ "14", "A", "PHE",], [ "15", "A", "ILE",], [ "16", "A", "ALA",], [ "33", "A", "THR",], [ "34", "A", "VAL",], [ "35", "A", "ARG",], [ "62", "A", "VAL",], [ "65", "A", "ILE",], [ "87", "A", "THR",], [ "88", "A", "ALA",], [ "89", "A", "SER",], [ "90", "A", "PRO",], [ "91", "A", "PHE",], [ "105", "A", "PRO",], [ "130", "A", "THR",], [ "132", "A", "SER",], [ "139", "A", "PHE",], [ "170", "A", "TYR",], [ "174", "A", "LYS",], [ "199", "A", "PRO",], [ "201", "A", "TYR",], [ "202", "A", "VAL",], [ "217", "A", "ASN",], [ "218", "A", "THR",], [ "219", "A", "SER",],]

[RESULTS.FREQUENCY.KAA.RESIDUES]
ALA = 2
ARG = 1
ASN = 1
ILE = 2
LYS = 1
PHE = 3
PRO = 3
SER = 4
THR = 4
TYR = 2
VAL = 3

[RESULTS.FREQUENCY.KAA.CLASS]
R1 = 10
R2 = 5
R3 = 9
R4 = 0
R5 = 2
RX = 0
