# pyKVFinder results

[FILES]
INPUT = "/mnt/bkup/Ssal-KRED_orthologs/HomoLogic_Ort-RDM_1_3_homologs_tested/08_homolog_bindingsites_superposed/EXU95441_superposed_bindingsite_refined.pdb"
OUTPUT = "/mnt/bkup/Ssal-KRED_orthologs/HomoLogic_Ort-RDM_1_3_homologs_tested/11_detected_cavities/EXU95441_cavities.pdb"

[PARAMETERS]
STEP = 0.6

[RESULTS.VOLUME]
KAA = 708.48

[RESULTS.AREA]
KAA = 478.41

[RESULTS.MAX_DEPTH]
KAA = 5.91

[RESULTS.AVG_DEPTH]
KAA = 2.1

[RESULTS.AVG_HYDROPATHY]
KAA = -0.38
EisenbergWeiss = [ -1.42, 2.6,]

[RESULTS.RESIDUES]
KAA = [ [ "14", "A", "THR",], [ "16", "A", "PHE",], [ "17", "A", "ILE",], [ "35", "A", "THR",], [ "36", "A", "ALA",], [ "37", "A", "ARG",], [ "41", "A", "SER",], [ "61", "A", "ILE",], [ "64", "A", "ILE",], [ "83", "A", "MET",], [ "84", "A", "ALA",], [ "85", "A", "SER",], [ "86", "A", "PRO",], [ "87", "A", "PHE",], [ "89", "A", "TYR",], [ "126", "A", "THR",], [ "128", "A", "SER",], [ "129", "A", "PHE",], [ "130", "A", "ALA",], [ "167", "A", "TYR",], [ "171", "A", "LYS",], [ "197", "A", "PRO",], [ "198", "A", "PRO",], [ "199", "A", "MET",], [ "200", "A", "VAL",], [ "213", "A", "HIS",], [ "216", "A", "GLN",], [ "217", "A", "SER",], [ "237", "A", "LEU",],]

[RESULTS.FREQUENCY.KAA.RESIDUES]
ALA = 3
ARG = 1
GLN = 1
HIS = 1
ILE = 3
LEU = 1
LYS = 1
MET = 2
PHE = 3
PRO = 3
SER = 4
THR = 3
TYR = 2
VAL = 1

[RESULTS.FREQUENCY.KAA.CLASS]
R1 = 11
R2 = 5
R3 = 10
R4 = 0
R5 = 3
RX = 0
