# pyKVFinder results

[FILES]
INPUT = "/mnt/bkup/Ssal-KRED_orthologs/HomoLogic_Ort-RDM_1_3_homologs_tested/08_homolog_bindingsites_superposed/KFA63262_superposed_bindingsite_refined.pdb"
OUTPUT = "/mnt/bkup/Ssal-KRED_orthologs/HomoLogic_Ort-RDM_1_3_homologs_tested/11_detected_cavities/KFA63262_cavities.pdb"

[PARAMETERS]
STEP = 0.6

[RESULTS.VOLUME]
KAA = 138.89
KAB = 526.61

[RESULTS.AREA]
KAA = 129.09
KAB = 305.65

[RESULTS.MAX_DEPTH]
KAA = 4.69
KAB = 3.89

[RESULTS.AVG_DEPTH]
KAA = 1.6
KAB = 1.32

[RESULTS.AVG_HYDROPATHY]
KAA = -0.15
KAB = -0.47
EisenbergWeiss = [ -1.42, 2.6,]

[RESULTS.RESIDUES]
KAA = [ [ "8", "A", "THR",], [ "11", "A", "THR",], [ "32", "A", "ILE",], [ "33", "A", "VAL",], [ "34", "A", "ARG",], [ "38", "A", "ASN",], [ "63", "A", "ILE",], [ "66", "A", "PHE",], [ "67", "A", "LEU",], [ "86", "A", "ALA",], [ "88", "A", "PRO",], [ "108", "A", "MET",],]
KAB = [ [ "13", "A", "TYR",], [ "14", "A", "ILE",], [ "85", "A", "LEU",], [ "86", "A", "ALA",], [ "87", "A", "SER",], [ "89", "A", "LEU",], [ "128", "A", "THR",], [ "130", "A", "SER",], [ "131", "A", "SER",], [ "132", "A", "VAL",], [ "160", "A", "MET",], [ "163", "A", "TYR",], [ "164", "A", "TRP",], [ "167", "A", "LYS",], [ "192", "A", "PRO",], [ "193", "A", "SER",], [ "194", "A", "VAL",], [ "195", "A", "VAL",], [ "215", "A", "THR",], [ "234", "A", "TYR",], [ "235", "A", "VAL",],]

[RESULTS.FREQUENCY.KAA.RESIDUES]
ALA = 1
ARG = 1
ASN = 1
ILE = 2
LEU = 1
MET = 1
PHE = 1
PRO = 1
THR = 2
VAL = 1

[RESULTS.FREQUENCY.KAA.CLASS]
R1 = 6
R2 = 1
R3 = 4
R4 = 0
R5 = 1
RX = 0

[RESULTS.FREQUENCY.KAB.RESIDUES]
ALA = 1
ILE = 1
LEU = 2
LYS = 1
MET = 1
PRO = 1
SER = 4
THR = 2
TRP = 1
TYR = 3
VAL = 4

[RESULTS.FREQUENCY.KAB.CLASS]
R1 = 9
R2 = 4
R3 = 7
R4 = 0
R5 = 1
RX = 0
