# pyKVFinder results

[FILES]
INPUT = "/mnt/bkup/Ssal-KRED_orthologs/HomoLogic_Ort-RDM_1_3_homologs_tested/08_homolog_bindingsites_superposed/KGT65805_superposed_bindingsite_refined.pdb"
OUTPUT = "/mnt/bkup/Ssal-KRED_orthologs/HomoLogic_Ort-RDM_1_3_homologs_tested/11_detected_cavities/KGT65805_cavities.pdb"

[PARAMETERS]
STEP = 0.6

[RESULTS.VOLUME]
KAA = 506.3

[RESULTS.AREA]
KAA = 401.93

[RESULTS.MAX_DEPTH]
KAA = 4.98

[RESULTS.AVG_DEPTH]
KAA = 1.6

[RESULTS.AVG_HYDROPATHY]
KAA = -0.31
EisenbergWeiss = [ -1.42, 2.6,]

[RESULTS.RESIDUES]
KAA = [ [ "13", "A", "THR",], [ "15", "A", "PHE",], [ "16", "A", "ILE",], [ "17", "A", "ALA",], [ "34", "A", "THR",], [ "35", "A", "VAL",], [ "36", "A", "ARG",], [ "59", "A", "VAL",], [ "62", "A", "VAL",], [ "84", "A", "LEU",], [ "85", "A", "ALA",], [ "86", "A", "SER",], [ "87", "A", "PRO",], [ "88", "A", "PHE",], [ "102", "A", "PRO",], [ "127", "A", "THR",], [ "129", "A", "SER",], [ "130", "A", "TYR",], [ "167", "A", "TYR",], [ "171", "A", "LYS",], [ "197", "A", "PRO",], [ "198", "A", "SER",], [ "199", "A", "PHE",], [ "200", "A", "VAL",], [ "215", "A", "ASN",], [ "217", "A", "SER",],]

[RESULTS.FREQUENCY.KAA.RESIDUES]
ALA = 2
ARG = 1
ASN = 1
ILE = 1
LEU = 1
LYS = 1
PHE = 3
PRO = 3
SER = 4
THR = 3
TYR = 2
VAL = 4

[RESULTS.FREQUENCY.KAA.CLASS]
R1 = 11
R2 = 5
R3 = 8
R4 = 0
R5 = 2
RX = 0
