# pyKVFinder results

[FILES]
INPUT = "/mnt/bkup/Ssal-KRED_orthologs/HomoLogic_Ort-RDM_1_3_homologs_tested/08_homolog_bindingsites_superposed/KJJ29487_superposed_bindingsite_refined.pdb"
OUTPUT = "/mnt/bkup/Ssal-KRED_orthologs/HomoLogic_Ort-RDM_1_3_homologs_tested/11_detected_cavities/KJJ29487_cavities.pdb"

[PARAMETERS]
STEP = 0.6

[RESULTS.VOLUME]
KAA = 705.46

[RESULTS.AREA]
KAA = 476.27

[RESULTS.MAX_DEPTH]
KAA = 4.72

[RESULTS.AVG_DEPTH]
KAA = 1.75

[RESULTS.AVG_HYDROPATHY]
KAA = -0.19
EisenbergWeiss = [ -1.42, 2.6,]

[RESULTS.RESIDUES]
KAA = [ [ "17", "A", "THR",], [ "20", "A", "ASN",], [ "22", "A", "PHE",], [ "23", "A", "ILE",], [ "41", "A", "THR",], [ "42", "A", "VAL",], [ "43", "A", "ARG",], [ "69", "A", "VAL",], [ "71", "A", "ASP",], [ "72", "A", "MET",], [ "78", "A", "PHE",], [ "91", "A", "VAL",], [ "92", "A", "ALA",], [ "93", "A", "THR",], [ "94", "A", "PRO",], [ "95", "A", "VAL",], [ "96", "A", "ARG",], [ "107", "A", "MET",], [ "131", "A", "THR",], [ "133", "A", "SER",], [ "134", "A", "SER",], [ "177", "A", "TYR",], [ "181", "A", "LYS",], [ "206", "A", "PRO",], [ "207", "A", "ASN",], [ "208", "A", "VAL",], [ "209", "A", "ASN",], [ "222", "A", "PRO",], [ "223", "A", "SER",], [ "224", "A", "SER",], [ "227", "A", "TRP",], [ "249", "A", "GLN",],]

[RESULTS.FREQUENCY.KAA.RESIDUES]
ALA = 1
ARG = 2
ASN = 3
ASP = 1
GLN = 1
ILE = 1
LYS = 1
MET = 2
PHE = 2
PRO = 3
SER = 4
THR = 4
TRP = 1
TYR = 1
VAL = 5

[RESULTS.FREQUENCY.KAA.CLASS]
R1 = 10
R2 = 4
R3 = 14
R4 = 1
R5 = 3
RX = 0
