# pyKVFinder results

[FILES]
INPUT = "/mnt/bkup/Ssal-KRED_orthologs/HomoLogic_Ort-RDM_1_3_homologs_tested/08_homolog_bindingsites_superposed/KYG41666_superposed_bindingsite_refined.pdb"
OUTPUT = "/mnt/bkup/Ssal-KRED_orthologs/HomoLogic_Ort-RDM_1_3_homologs_tested/11_detected_cavities/KYG41666_cavities.pdb"

[PARAMETERS]
STEP = 0.6

[RESULTS.VOLUME]
KAA = 745.85

[RESULTS.AREA]
KAA = 514.76

[RESULTS.MAX_DEPTH]
KAA = 7.82

[RESULTS.AVG_DEPTH]
KAA = 2.73

[RESULTS.AVG_HYDROPATHY]
KAA = -0.19
EisenbergWeiss = [ -1.42, 2.6,]

[RESULTS.RESIDUES]
KAA = [ [ "24", "A", "THR",], [ "26", "A", "TYR",], [ "27", "A", "ILE",], [ "45", "A", "THR",], [ "46", "A", "THR",], [ "47", "A", "ARG",], [ "51", "A", "LYS",], [ "73", "A", "VAL",], [ "76", "A", "MET",], [ "82", "A", "TYR",], [ "95", "A", "LEU",], [ "96", "A", "ALA",], [ "97", "A", "SER",], [ "99", "A", "LEU",], [ "101", "A", "PHE",], [ "135", "A", "THR",], [ "137", "A", "SER",], [ "138", "A", "SER",], [ "139", "A", "THR",], [ "174", "A", "PHE",], [ "177", "A", "TYR",], [ "181", "A", "LYS",], [ "206", "A", "PRO",], [ "207", "A", "ASN",], [ "208", "A", "MET",], [ "209", "A", "ASN",], [ "223", "A", "SER",], [ "224", "A", "THR",], [ "227", "A", "TRP",], [ "241", "A", "PHE",], [ "244", "A", "GLN",],]

[RESULTS.FREQUENCY.KAA.RESIDUES]
ALA = 1
ARG = 1
ASN = 2
GLN = 1
ILE = 1
LEU = 2
LYS = 2
MET = 2
PHE = 3
PRO = 1
SER = 4
THR = 6
TRP = 1
TYR = 3
VAL = 1

[RESULTS.FREQUENCY.KAA.CLASS]
R1 = 6
R2 = 7
R3 = 15
R4 = 0
R5 = 3
RX = 0
