# pyKVFinder results

[FILES]
INPUT = "/mnt/bkup/Ssal-KRED_orthologs/HomoLogic_Ort-RDM_1_3_homologs_tested/08_homolog_bindingsites_superposed/KZP19288_superposed_bindingsite_refined.pdb"
OUTPUT = "/mnt/bkup/Ssal-KRED_orthologs/HomoLogic_Ort-RDM_1_3_homologs_tested/11_detected_cavities/KZP19288_cavities.pdb"

[PARAMETERS]
STEP = 0.6

[RESULTS.VOLUME]
KAA = 543.46

[RESULTS.AREA]
KAA = 400.39

[RESULTS.MAX_DEPTH]
KAA = 5.4

[RESULTS.AVG_DEPTH]
KAA = 1.79

[RESULTS.AVG_HYDROPATHY]
KAA = -0.11
EisenbergWeiss = [ -1.42, 2.6,]

[RESULTS.RESIDUES]
KAA = [ [ "13", "A", "THR",], [ "16", "A", "ASN",], [ "18", "A", "PHE",], [ "19", "A", "ILE",], [ "20", "A", "ALA",], [ "37", "A", "THR",], [ "39", "A", "ARG",], [ "43", "A", "LYS",], [ "65", "A", "VAL",], [ "68", "A", "MET",], [ "74", "A", "PHE",], [ "87", "A", "VAL",], [ "88", "A", "ALA",], [ "89", "A", "SER",], [ "90", "A", "ILE",], [ "91", "A", "MET",], [ "131", "A", "THR",], [ "133", "A", "SER",], [ "134", "A", "ALA",], [ "176", "A", "TYR",], [ "180", "A", "LYS",], [ "205", "A", "PRO",], [ "206", "A", "ASN",], [ "207", "A", "VAL",], [ "208", "A", "ASN",], [ "219", "A", "ARG",], [ "220", "A", "SER",], [ "221", "A", "SER",], [ "242", "A", "GLN",],]

[RESULTS.FREQUENCY.KAA.RESIDUES]
ALA = 3
ARG = 2
ASN = 3
GLN = 1
ILE = 2
LYS = 2
MET = 2
PHE = 2
PRO = 1
SER = 4
THR = 3
TYR = 1
VAL = 3

[RESULTS.FREQUENCY.KAA.CLASS]
R1 = 9
R2 = 3
R3 = 13
R4 = 0
R5 = 4
RX = 0
