# pyKVFinder results

[FILES]
INPUT = "/mnt/bkup/Ssal-KRED_orthologs/HomoLogic_Ort-RDM_1_3_homologs_tested/08_homolog_bindingsites_superposed/ODV67907_superposed_bindingsite_refined.pdb"
OUTPUT = "/mnt/bkup/Ssal-KRED_orthologs/HomoLogic_Ort-RDM_1_3_homologs_tested/11_detected_cavities/ODV67907_cavities.pdb"

[PARAMETERS]
STEP = 0.6

[RESULTS.VOLUME]
KAA = 104.11
KAB = 308.45

[RESULTS.AREA]
KAA = 90.36
KAB = 242.83

[RESULTS.MAX_DEPTH]
KAA = 2.16
KAB = 4.07

[RESULTS.AVG_DEPTH]
KAA = 0.72
KAB = 1.57

[RESULTS.AVG_HYDROPATHY]
KAA = 0.16
KAB = -0.44
EisenbergWeiss = [ -1.42, 2.6,]

[RESULTS.RESIDUES]
KAA = [ [ "13", "A", "THR",], [ "34", "A", "SER",], [ "35", "A", "VAL",], [ "36", "A", "ARG",], [ "58", "A", "VAL",], [ "61", "A", "ILE",], [ "84", "A", "ALA",], [ "86", "A", "PRO",], [ "101", "A", "PRO",],]
KAB = [ [ "15", "A", "PHE",], [ "16", "A", "ILE",], [ "17", "A", "ALA",], [ "83", "A", "THR",], [ "84", "A", "ALA",], [ "85", "A", "SER",], [ "87", "A", "PHE",], [ "126", "A", "THR",], [ "128", "A", "SER",], [ "166", "A", "TYR",], [ "170", "A", "LYS",], [ "195", "A", "PRO",], [ "197", "A", "TYR",], [ "198", "A", "VAL",], [ "215", "A", "SER",],]

[RESULTS.FREQUENCY.KAA.RESIDUES]
ALA = 1
ARG = 1
ILE = 1
PRO = 2
SER = 1
THR = 1
VAL = 2

[RESULTS.FREQUENCY.KAA.CLASS]
R1 = 6
R2 = 0
R3 = 2
R4 = 0
R5 = 1
RX = 0

[RESULTS.FREQUENCY.KAB.RESIDUES]
ALA = 2
ILE = 1
LYS = 1
PHE = 2
PRO = 1
SER = 3
THR = 2
TYR = 2
VAL = 1

[RESULTS.FREQUENCY.KAB.CLASS]
R1 = 5
R2 = 4
R3 = 5
R4 = 0
R5 = 1
RX = 0
