# pyKVFinder results

[FILES]
INPUT = "/mnt/bkup/Ssal-KRED_orthologs/HomoLogic_Ort-RDM_1_3_homologs_tested/08_homolog_bindingsites_superposed/ODV76726_superposed_bindingsite_refined.pdb"
OUTPUT = "/mnt/bkup/Ssal-KRED_orthologs/HomoLogic_Ort-RDM_1_3_homologs_tested/11_detected_cavities/ODV76726_cavities.pdb"

[PARAMETERS]
STEP = 0.6

[RESULTS.VOLUME]
KAA = 575.21

[RESULTS.AREA]
KAA = 459.54

[RESULTS.MAX_DEPTH]
KAA = 6.12

[RESULTS.AVG_DEPTH]
KAA = 2.05

[RESULTS.AVG_HYDROPATHY]
KAA = -0.34
EisenbergWeiss = [ -1.42, 2.6,]

[RESULTS.RESIDUES]
KAA = [ [ "10", "A", "THR",], [ "12", "A", "PHE",], [ "13", "A", "ILE",], [ "14", "A", "ALA",], [ "31", "A", "SER",], [ "32", "A", "VAL",], [ "33", "A", "ARG",], [ "54", "A", "VAL",], [ "57", "A", "ILE",], [ "79", "A", "THR",], [ "80", "A", "ALA",], [ "81", "A", "SER",], [ "82", "A", "PRO",], [ "83", "A", "PHE",], [ "85", "A", "TYR",], [ "97", "A", "PRO",], [ "122", "A", "THR",], [ "124", "A", "SER",], [ "125", "A", "VAL",], [ "126", "A", "ALA",], [ "162", "A", "PHE",], [ "165", "A", "TYR",], [ "169", "A", "LYS",], [ "194", "A", "PRO",], [ "195", "A", "SER",], [ "196", "A", "PHE",], [ "197", "A", "VAL",], [ "214", "A", "SER",],]

[RESULTS.FREQUENCY.KAA.RESIDUES]
ALA = 3
ARG = 1
ILE = 2
LYS = 1
PHE = 4
PRO = 3
SER = 5
THR = 3
TYR = 2
VAL = 4

[RESULTS.FREQUENCY.KAA.CLASS]
R1 = 12
R2 = 6
R3 = 8
R4 = 0
R5 = 2
RX = 0
