# pyKVFinder results

[FILES]
INPUT = "/mnt/bkup/Ssal-KRED_orthologs/HomoLogic_Ort-RDM_1_3_homologs_tested/08_homolog_bindingsites_superposed/POY72851_superposed_bindingsite_refined.pdb"
OUTPUT = "/mnt/bkup/Ssal-KRED_orthologs/HomoLogic_Ort-RDM_1_3_homologs_tested/11_detected_cavities/POY72851_cavities.pdb"

[PARAMETERS]
STEP = 0.6

[RESULTS.VOLUME]
KAA = 574.56

[RESULTS.AREA]
KAA = 419.5

[RESULTS.MAX_DEPTH]
KAA = 4.87

[RESULTS.AVG_DEPTH]
KAA = 1.79

[RESULTS.AVG_HYDROPATHY]
KAA = -0.22
EisenbergWeiss = [ -1.42, 2.6,]

[RESULTS.RESIDUES]
KAA = [ [ "13", "A", "SER",], [ "16", "A", "SER",], [ "18", "A", "TYR",], [ "19", "A", "LEU",], [ "37", "A", "THR",], [ "38", "A", "VAL",], [ "39", "A", "ARG",], [ "43", "A", "LYS",], [ "64", "A", "VAL",], [ "67", "A", "VAL",], [ "86", "A", "THR",], [ "87", "A", "ALA",], [ "88", "A", "SER",], [ "89", "A", "PRO",], [ "90", "A", "PHE",], [ "104", "A", "PRO",], [ "128", "A", "THR",], [ "130", "A", "SER",], [ "171", "A", "TYR",], [ "175", "A", "LYS",], [ "200", "A", "PRO",], [ "201", "A", "PRO",], [ "202", "A", "LEU",], [ "203", "A", "ILE",], [ "218", "A", "ASN",], [ "220", "A", "SER",],]

[RESULTS.FREQUENCY.KAA.RESIDUES]
ALA = 1
ARG = 1
ASN = 1
ILE = 1
LEU = 2
LYS = 2
PHE = 1
PRO = 4
SER = 5
THR = 3
TYR = 2
VAL = 3

[RESULTS.FREQUENCY.KAA.CLASS]
R1 = 11
R2 = 3
R3 = 9
R4 = 0
R5 = 3
RX = 0
