# pyKVFinder results

[FILES]
INPUT = "/mnt/bkup/peter_ccfour/Documents/KRED_Niklaus/000_final/000_homologic_2b_R_best/08_homolog_bindingsites_superposed/ABN66052_superposed_bindingsite_refined.pdb"
OUTPUT = "/mnt/bkup/peter_ccfour/Documents/KRED_Niklaus/000_final/000_homologic_2b_R_best/11_detected_cavities/ABN66052_cavities.pdb"

[PARAMETERS]
STEP = 0.6

[RESULTS.VOLUME]
KAA = 127.01
KAB = 324.22

[RESULTS.AREA]
KAA = 113.26
KAB = 247.63

[RESULTS.MAX_DEPTH]
KAA = 2.4
KAB = 3.84

[RESULTS.AVG_DEPTH]
KAA = 0.86
KAB = 1.47

[RESULTS.AVG_HYDROPATHY]
KAA = 0.23
KAB = -0.49
EisenbergWeiss = [ -1.42, 2.6,]

[RESULTS.RESIDUES]
KAA = [ [ "7", "A", "SER",], [ "10", "A", "THR",], [ "31", "A", "SER",], [ "32", "A", "VAL",], [ "33", "A", "ARG",], [ "55", "A", "VAL",], [ "58", "A", "ILE",], [ "81", "A", "ALA",], [ "83", "A", "PRO",], [ "98", "A", "PRO",],]
KAB = [ [ "12", "A", "PHE",], [ "13", "A", "ILE",], [ "14", "A", "ALA",], [ "80", "A", "THR",], [ "81", "A", "ALA",], [ "82", "A", "SER",], [ "84", "A", "PHE",], [ "123", "A", "THR",], [ "125", "A", "SER",], [ "163", "A", "TYR",], [ "167", "A", "LYS",], [ "192", "A", "PRO",], [ "193", "A", "THR",], [ "194", "A", "PHE",], [ "195", "A", "VAL",], [ "210", "A", "ASN",], [ "212", "A", "SER",],]

[RESULTS.FREQUENCY.KAA.RESIDUES]
ALA = 1
ARG = 1
ILE = 1
PRO = 2
SER = 2
THR = 1
VAL = 2

[RESULTS.FREQUENCY.KAA.CLASS]
R1 = 6
R2 = 0
R3 = 3
R4 = 0
R5 = 1
RX = 0

[RESULTS.FREQUENCY.KAB.RESIDUES]
ALA = 2
ASN = 1
ILE = 1
LYS = 1
PHE = 3
PRO = 1
SER = 3
THR = 3
TYR = 1
VAL = 1

[RESULTS.FREQUENCY.KAB.CLASS]
R1 = 5
R2 = 4
R3 = 7
R4 = 0
R5 = 1
RX = 0
