# pyKVFinder results

[FILES]
INPUT = "/mnt/bkup/peter_ccfour/Documents/KRED_Niklaus/000_final/000_homologic_2b_R_best/08_homolog_bindingsites_superposed/CAX43883_superposed_bindingsite_refined.pdb"
OUTPUT = "/mnt/bkup/peter_ccfour/Documents/KRED_Niklaus/000_final/000_homologic_2b_R_best/11_detected_cavities/CAX43883_cavities.pdb"

[PARAMETERS]
STEP = 0.6

[RESULTS.VOLUME]
KAA = 597.89

[RESULTS.AREA]
KAA = 427.87

[RESULTS.MAX_DEPTH]
KAA = 5.4

[RESULTS.AVG_DEPTH]
KAA = 1.54

[RESULTS.AVG_HYDROPATHY]
KAA = -0.13
EisenbergWeiss = [ -1.42, 2.6,]

[RESULTS.RESIDUES]
KAA = [ [ "9", "A", "THR",], [ "12", "A", "THR",], [ "14", "A", "TYR",], [ "15", "A", "ILE",], [ "16", "A", "ALA",], [ "33", "A", "SER",], [ "34", "A", "VAL",], [ "35", "A", "ARG",], [ "39", "A", "LYS",], [ "65", "A", "VAL",], [ "68", "A", "LEU",], [ "90", "A", "THR",], [ "91", "A", "ALA",], [ "92", "A", "SER",], [ "93", "A", "PRO",], [ "94", "A", "ILE",], [ "95", "A", "PRO",], [ "108", "A", "PRO",], [ "134", "A", "THR",], [ "136", "A", "SER",], [ "137", "A", "ILE",], [ "138", "A", "ALA",], [ "174", "A", "TYR",], [ "175", "A", "TYR",], [ "178", "A", "LYS",], [ "208", "A", "PRO",], [ "210", "A", "PHE",], [ "211", "A", "VAL",], [ "227", "A", "ARG",], [ "228", "A", "SER",], [ "229", "A", "SER",],]

[RESULTS.FREQUENCY.KAA.RESIDUES]
ALA = 3
ARG = 2
ILE = 3
LEU = 1
LYS = 2
PHE = 1
PRO = 4
SER = 5
THR = 4
TYR = 3
VAL = 3

[RESULTS.FREQUENCY.KAA.CLASS]
R1 = 14
R2 = 4
R3 = 9
R4 = 0
R5 = 4
RX = 0
