# pyKVFinder results

[FILES]
INPUT = "/mnt/bkup/peter_ccfour/Documents/KRED_Niklaus/000_final/000_homologic_2b_R_best/08_homolog_bindingsites_superposed/CCG25156_superposed_bindingsite_refined.pdb"
OUTPUT = "/mnt/bkup/peter_ccfour/Documents/KRED_Niklaus/000_final/000_homologic_2b_R_best/11_detected_cavities/CCG25156_cavities.pdb"

[PARAMETERS]
STEP = 0.6

[RESULTS.VOLUME]
KAA = 409.75

[RESULTS.AREA]
KAA = 248.66

[RESULTS.MAX_DEPTH]
KAA = 3.29

[RESULTS.AVG_DEPTH]
KAA = 1.05

[RESULTS.AVG_HYDROPATHY]
KAA = -0.37
EisenbergWeiss = [ -1.42, 2.6,]

[RESULTS.RESIDUES]
KAA = [ [ "18", "A", "TYR",], [ "19", "A", "VAL",], [ "86", "A", "SER",], [ "88", "A", "ALA",], [ "90", "A", "VAL",], [ "91", "A", "PRO",], [ "130", "A", "THR",], [ "132", "A", "SER",], [ "133", "A", "THR",], [ "134", "A", "ALA",], [ "143", "A", "PHE",], [ "170", "A", "TYR",], [ "171", "A", "PHE",], [ "174", "A", "LYS",], [ "199", "A", "PRO",], [ "200", "A", "SER",], [ "201", "A", "PHE",], [ "202", "A", "CYS",], [ "219", "A", "SER",], [ "220", "A", "SER",],]

[RESULTS.FREQUENCY.KAA.RESIDUES]
ALA = 2
CYS = 1
LYS = 1
PHE = 3
PRO = 2
SER = 5
THR = 2
TYR = 2
VAL = 2

[RESULTS.FREQUENCY.KAA.CLASS]
R1 = 6
R2 = 5
R3 = 8
R4 = 0
R5 = 1
RX = 0
