# pyKVFinder results

[FILES]
INPUT = "/mnt/bkup/peter_ccfour/Documents/KRED_Niklaus/000_final/000_homologic_2b_R_best/08_homolog_bindingsites_superposed/CCH60145_superposed_bindingsite_refined.pdb"
OUTPUT = "/mnt/bkup/peter_ccfour/Documents/KRED_Niklaus/000_final/000_homologic_2b_R_best/11_detected_cavities/CCH60145_cavities.pdb"

[PARAMETERS]
STEP = 0.6

[RESULTS.VOLUME]
KAA = 517.97

[RESULTS.AREA]
KAA = 389.29

[RESULTS.MAX_DEPTH]
KAA = 4.8

[RESULTS.AVG_DEPTH]
KAA = 1.53

[RESULTS.AVG_HYDROPATHY]
KAA = -0.23
EisenbergWeiss = [ -1.42, 2.6,]

[RESULTS.RESIDUES]
KAA = [ [ "9", "A", "THR",], [ "11", "A", "TYR",], [ "12", "A", "ILE",], [ "13", "A", "ALA",], [ "30", "A", "THR",], [ "32", "A", "ARG",], [ "54", "A", "VAL",], [ "57", "A", "ILE",], [ "80", "A", "THR",], [ "81", "A", "ALA",], [ "82", "A", "SER",], [ "83", "A", "PRO",], [ "84", "A", "VAL",], [ "124", "A", "THR",], [ "126", "A", "SER",], [ "127", "A", "VAL",], [ "128", "A", "ALA",], [ "164", "A", "TYR",], [ "165", "A", "PHE",], [ "168", "A", "LYS",], [ "197", "A", "PRO",], [ "199", "A", "TYR",], [ "200", "A", "VAL",], [ "215", "A", "ASN",], [ "216", "A", "PHE",], [ "217", "A", "SER",],]

[RESULTS.FREQUENCY.KAA.RESIDUES]
ALA = 3
ARG = 1
ASN = 1
ILE = 2
LYS = 1
PHE = 2
PRO = 2
SER = 3
THR = 4
TYR = 3
VAL = 4

[RESULTS.FREQUENCY.KAA.CLASS]
R1 = 11
R2 = 5
R3 = 8
R4 = 0
R5 = 2
RX = 0
