# pyKVFinder results

[FILES]
INPUT = "/mnt/bkup/peter_ccfour/Documents/KRED_Niklaus/000_final/000_homologic_2b_R_best/08_homolog_bindingsites_superposed/EDK41009_superposed_bindingsite_refined.pdb"
OUTPUT = "/mnt/bkup/peter_ccfour/Documents/KRED_Niklaus/000_final/000_homologic_2b_R_best/11_detected_cavities/EDK41009_cavities.pdb"

[PARAMETERS]
STEP = 0.6

[RESULTS.VOLUME]
KAA = 611.28

[RESULTS.AREA]
KAA = 434.28

[RESULTS.MAX_DEPTH]
KAA = 5.53

[RESULTS.AVG_DEPTH]
KAA = 1.75

[RESULTS.AVG_HYDROPATHY]
KAA = -0.24
EisenbergWeiss = [ -1.42, 2.6,]

[RESULTS.RESIDUES]
KAA = [ [ "11", "A", "SER",], [ "13", "A", "PHE",], [ "14", "A", "ILE",], [ "15", "A", "ALA",], [ "32", "A", "SER",], [ "34", "A", "ARG",], [ "38", "A", "LYS",], [ "55", "A", "VAL",], [ "58", "A", "ILE",], [ "80", "A", "THR",], [ "81", "A", "ALA",], [ "82", "A", "SER",], [ "83", "A", "PRO",], [ "84", "A", "PHE",], [ "98", "A", "PRO",], [ "123", "A", "THR",], [ "125", "A", "SER",], [ "126", "A", "PHE",], [ "163", "A", "TYR",], [ "167", "A", "LYS",], [ "192", "A", "PRO",], [ "193", "A", "THR",], [ "194", "A", "TYR",], [ "195", "A", "VAL",], [ "210", "A", "ASN",], [ "212", "A", "SER",], [ "234", "A", "PRO",],]

[RESULTS.FREQUENCY.KAA.RESIDUES]
ALA = 2
ARG = 1
ASN = 1
ILE = 2
LYS = 2
PHE = 3
PRO = 4
SER = 5
THR = 3
TYR = 2
VAL = 2

[RESULTS.FREQUENCY.KAA.CLASS]
R1 = 10
R2 = 5
R3 = 9
R4 = 0
R5 = 3
RX = 0
