# pyKVFinder results

[FILES]
INPUT = "/mnt/bkup/peter_ccfour/Documents/KRED_Niklaus/000_final/000_homologic_2b_R_best/08_homolog_bindingsites_superposed/EDK46659_superposed_bindingsite_refined.pdb"
OUTPUT = "/mnt/bkup/peter_ccfour/Documents/KRED_Niklaus/000_final/000_homologic_2b_R_best/11_detected_cavities/EDK46659_cavities.pdb"

[PARAMETERS]
STEP = 0.6

[RESULTS.VOLUME]
KAA = 116.86
KAB = 305.64

[RESULTS.AREA]
KAA = 108.33
KAB = 242.65

[RESULTS.MAX_DEPTH]
KAA = 2.4
KAB = 3.7

[RESULTS.AVG_DEPTH]
KAA = 0.88
KAB = 1.39

[RESULTS.AVG_HYDROPATHY]
KAA = 0.44
KAB = -0.45
EisenbergWeiss = [ -1.42, 2.6,]

[RESULTS.RESIDUES]
KAA = [ [ "11", "A", "THR",], [ "32", "A", "THR",], [ "34", "A", "ARG",], [ "57", "A", "VAL",], [ "59", "A", "ASP",], [ "60", "A", "VAL",], [ "83", "A", "ALA",], [ "85", "A", "PRO",], [ "100", "A", "PRO",],]
KAB = [ [ "13", "A", "PHE",], [ "14", "A", "ILE",], [ "15", "A", "ALA",], [ "82", "A", "THR",], [ "84", "A", "SER",], [ "86", "A", "PHE",], [ "125", "A", "THR",], [ "127", "A", "SER",], [ "128", "A", "PHE",], [ "165", "A", "TYR",], [ "169", "A", "LYS",], [ "194", "A", "PRO",], [ "195", "A", "THR",], [ "196", "A", "PHE",], [ "197", "A", "VAL",], [ "212", "A", "ASN",], [ "214", "A", "SER",],]

[RESULTS.FREQUENCY.KAA.RESIDUES]
ALA = 1
ARG = 1
ASP = 1
PRO = 2
THR = 2
VAL = 2

[RESULTS.FREQUENCY.KAA.CLASS]
R1 = 5
R2 = 0
R3 = 2
R4 = 1
R5 = 1
RX = 0

[RESULTS.FREQUENCY.KAB.RESIDUES]
ALA = 1
ASN = 1
ILE = 1
LYS = 1
PHE = 4
PRO = 1
SER = 3
THR = 3
TYR = 1
VAL = 1

[RESULTS.FREQUENCY.KAB.CLASS]
R1 = 4
R2 = 5
R3 = 7
R4 = 0
R5 = 1
RX = 0
