# pyKVFinder results

[FILES]
INPUT = "/mnt/bkup/peter_ccfour/Documents/KRED_Niklaus/000_final/000_homologic_2b_R_best/08_homolog_bindingsites_superposed/EER30950_superposed_bindingsite_refined.pdb"
OUTPUT = "/mnt/bkup/peter_ccfour/Documents/KRED_Niklaus/000_final/000_homologic_2b_R_best/11_detected_cavities/EER30950_cavities.pdb"

[PARAMETERS]
STEP = 0.6

[RESULTS.VOLUME]
KAA = 109.3
KAB = 332.42

[RESULTS.AREA]
KAA = 94.75
KAB = 265.16

[RESULTS.MAX_DEPTH]
KAA = 2.4
KAB = 3.84

[RESULTS.AVG_DEPTH]
KAA = 0.75
KAB = 1.37

[RESULTS.AVG_HYDROPATHY]
KAA = 0.32
KAB = -0.56
EisenbergWeiss = [ -1.42, 2.6,]

[RESULTS.RESIDUES]
KAA = [ [ "10", "A", "THR",], [ "31", "A", "THR",], [ "32", "A", "VAL",], [ "33", "A", "ARG",], [ "56", "A", "VAL",], [ "58", "A", "ASP",], [ "59", "A", "VAL",], [ "82", "A", "ALA",], [ "84", "A", "PRO",], [ "99", "A", "PRO",],]
KAB = [ [ "12", "A", "PHE",], [ "13", "A", "ILE",], [ "14", "A", "ALA",], [ "80", "A", "HIS",], [ "81", "A", "LEU",], [ "82", "A", "ALA",], [ "83", "A", "SER",], [ "85", "A", "PHE",], [ "124", "A", "THR",], [ "126", "A", "SER",], [ "127", "A", "TYR",], [ "164", "A", "TYR",], [ "168", "A", "LYS",], [ "195", "A", "PRO",], [ "196", "A", "SER",], [ "197", "A", "PHE",], [ "198", "A", "VAL",], [ "214", "A", "ASN",], [ "216", "A", "SER",],]

[RESULTS.FREQUENCY.KAA.RESIDUES]
ALA = 1
ARG = 1
ASP = 1
PRO = 2
THR = 2
VAL = 3

[RESULTS.FREQUENCY.KAA.CLASS]
R1 = 6
R2 = 0
R3 = 2
R4 = 1
R5 = 1
RX = 0

[RESULTS.FREQUENCY.KAB.RESIDUES]
ALA = 2
ASN = 1
HIS = 1
ILE = 1
LEU = 1
LYS = 1
PHE = 3
PRO = 1
SER = 4
THR = 1
TYR = 2
VAL = 1

[RESULTS.FREQUENCY.KAB.CLASS]
R1 = 6
R2 = 5
R3 = 6
R4 = 0
R5 = 2
RX = 0
