# pyKVFinder results

[FILES]
INPUT = "/mnt/bkup/peter_ccfour/Documents/KRED_Niklaus/000_final/000_homologic_2b_R_best/08_homolog_bindingsites_superposed/KGT65116_superposed_bindingsite_refined.pdb"
OUTPUT = "/mnt/bkup/peter_ccfour/Documents/KRED_Niklaus/000_final/000_homologic_2b_R_best/11_detected_cavities/KGT65116_cavities.pdb"

[PARAMETERS]
STEP = 0.6

[RESULTS.VOLUME]
KAA = 499.18

[RESULTS.AREA]
KAA = 359.27

[RESULTS.MAX_DEPTH]
KAA = 3.5

[RESULTS.AVG_DEPTH]
KAA = 1.09

[RESULTS.AVG_HYDROPATHY]
KAA = -0.32
EisenbergWeiss = [ -1.42, 2.6,]

[RESULTS.RESIDUES]
KAA = [ [ "11", "A", "SER",], [ "13", "A", "TYR",], [ "14", "A", "ILE",], [ "33", "A", "VAL",], [ "34", "A", "ARG",], [ "60", "A", "PHE",], [ "61", "A", "ASP",], [ "82", "A", "THR",], [ "83", "A", "ALA",], [ "84", "A", "ALA",], [ "85", "A", "VAL",], [ "86", "A", "VAL",], [ "88", "A", "PHE",], [ "100", "A", "PRO",], [ "104", "A", "LEU",], [ "125", "A", "THR",], [ "127", "A", "SER",], [ "128", "A", "SER",], [ "129", "A", "ALA",], [ "165", "A", "TYR",], [ "166", "A", "PHE",], [ "169", "A", "LYS",], [ "194", "A", "PRO",], [ "196", "A", "LEU",], [ "197", "A", "ILE",], [ "214", "A", "SER",], [ "215", "A", "THR",],]

[RESULTS.FREQUENCY.KAA.RESIDUES]
ALA = 3
ARG = 1
ASP = 1
ILE = 2
LEU = 2
LYS = 1
PHE = 3
PRO = 2
SER = 4
THR = 3
TYR = 2
VAL = 3

[RESULTS.FREQUENCY.KAA.CLASS]
R1 = 12
R2 = 5
R3 = 7
R4 = 1
R5 = 2
RX = 0
