# pyKVFinder results

[FILES]
INPUT = "/mnt/bkup/peter_ccfour/Documents/KRED_Niklaus/000_final/000_homologic_2b_R_best/08_homolog_bindingsites_superposed/KOH48093_superposed_bindingsite_refined.pdb"
OUTPUT = "/mnt/bkup/peter_ccfour/Documents/KRED_Niklaus/000_final/000_homologic_2b_R_best/11_detected_cavities/KOH48093_cavities.pdb"

[PARAMETERS]
STEP = 0.6

[RESULTS.VOLUME]
KAA = 110.81
KAB = 332.86

[RESULTS.AREA]
KAA = 97.8
KAB = 257.47

[RESULTS.MAX_DEPTH]
KAA = 3.0
KAB = 3.6

[RESULTS.AVG_DEPTH]
KAA = 1.1
KAB = 1.42

[RESULTS.AVG_HYDROPATHY]
KAA = 0.12
KAB = -0.43
EisenbergWeiss = [ -1.42, 2.6,]

[RESULTS.RESIDUES]
KAA = [ [ "6", "A", "SER",], [ "9", "A", "ASN",], [ "30", "A", "SER",], [ "31", "A", "ALA",], [ "32", "A", "ARG",], [ "55", "A", "VAL",], [ "58", "A", "ILE",], [ "64", "A", "PHE",], [ "82", "A", "ALA",], [ "84", "A", "PRO",],]
KAB = [ [ "11", "A", "PHE",], [ "12", "A", "ILE",], [ "13", "A", "ALA",], [ "81", "A", "THR",], [ "82", "A", "ALA",], [ "83", "A", "SER",], [ "85", "A", "PHE",], [ "125", "A", "THR",], [ "127", "A", "SER",], [ "128", "A", "TYR",], [ "165", "A", "TYR",], [ "169", "A", "LYS",], [ "196", "A", "PRO",], [ "197", "A", "VAL",], [ "198", "A", "TYR",], [ "199", "A", "VAL",], [ "214", "A", "ASN",], [ "216", "A", "SER",],]

[RESULTS.FREQUENCY.KAA.RESIDUES]
ALA = 2
ARG = 1
ASN = 1
ILE = 1
PHE = 1
PRO = 1
SER = 2
VAL = 1

[RESULTS.FREQUENCY.KAA.CLASS]
R1 = 5
R2 = 1
R3 = 3
R4 = 0
R5 = 1
RX = 0

[RESULTS.FREQUENCY.KAB.RESIDUES]
ALA = 2
ASN = 1
ILE = 1
LYS = 1
PHE = 2
PRO = 1
SER = 3
THR = 2
TYR = 3
VAL = 2

[RESULTS.FREQUENCY.KAB.CLASS]
R1 = 6
R2 = 5
R3 = 6
R4 = 0
R5 = 1
RX = 0
