# pyKVFinder results

[FILES]
INPUT = "/mnt/bkup/peter_ccfour/Documents/KRED_Niklaus/000_final/000_homologic_2b_R_best/08_homolog_bindingsites_superposed/KRZ99698_superposed_bindingsite_refined.pdb"
OUTPUT = "/mnt/bkup/peter_ccfour/Documents/KRED_Niklaus/000_final/000_homologic_2b_R_best/11_detected_cavities/KRZ99698_cavities.pdb"

[PARAMETERS]
STEP = 0.6

[RESULTS.VOLUME]
KAA = 479.74

[RESULTS.AREA]
KAA = 370.41

[RESULTS.MAX_DEPTH]
KAA = 4.2

[RESULTS.AVG_DEPTH]
KAA = 1.4

[RESULTS.AVG_HYDROPATHY]
KAA = -0.25
EisenbergWeiss = [ -1.42, 2.6,]

[RESULTS.RESIDUES]
KAA = [ [ "10", "A", "THR",], [ "12", "A", "TYR",], [ "13", "A", "ILE",], [ "14", "A", "ALA",], [ "31", "A", "SER",], [ "32", "A", "VAL",], [ "33", "A", "ARG",], [ "55", "A", "VAL",], [ "58", "A", "ILE",], [ "80", "A", "THR",], [ "81", "A", "ALA",], [ "82", "A", "SER",], [ "83", "A", "PRO",], [ "84", "A", "PHE",], [ "98", "A", "PRO",], [ "123", "A", "THR",], [ "125", "A", "SER",], [ "126", "A", "ILE",], [ "163", "A", "TYR",], [ "167", "A", "LYS",], [ "192", "A", "PRO",], [ "194", "A", "LEU",], [ "195", "A", "VAL",], [ "210", "A", "ASN",], [ "212", "A", "SER",],]

[RESULTS.FREQUENCY.KAA.RESIDUES]
ALA = 2
ARG = 1
ASN = 1
ILE = 3
LEU = 1
LYS = 1
PHE = 1
PRO = 3
SER = 4
THR = 3
TYR = 2
VAL = 3

[RESULTS.FREQUENCY.KAA.CLASS]
R1 = 12
R2 = 3
R3 = 8
R4 = 0
R5 = 2
RX = 0
