# pyKVFinder results

[FILES]
INPUT = "/mnt/bkup/peter_ccfour/Documents/KRED_Niklaus/000_final/000_homologic_2b_R_best/08_homolog_bindingsites_superposed/ODV77212_superposed_bindingsite_refined.pdb"
OUTPUT = "/mnt/bkup/peter_ccfour/Documents/KRED_Niklaus/000_final/000_homologic_2b_R_best/11_detected_cavities/ODV77212_cavities.pdb"

[PARAMETERS]
STEP = 0.6

[RESULTS.VOLUME]
KAA = 712.37

[RESULTS.AREA]
KAA = 501.37

[RESULTS.MAX_DEPTH]
KAA = 4.33

[RESULTS.AVG_DEPTH]
KAA = 1.65

[RESULTS.AVG_HYDROPATHY]
KAA = -0.29
EisenbergWeiss = [ -1.42, 2.6,]

[RESULTS.RESIDUES]
KAA = [ [ "10", "A", "THR",], [ "12", "A", "PHE",], [ "13", "A", "ILE",], [ "14", "A", "ALA",], [ "31", "A", "THR",], [ "32", "A", "VAL",], [ "33", "A", "ARG",], [ "37", "A", "LYS",], [ "55", "A", "VAL",], [ "58", "A", "LEU",], [ "80", "A", "THR",], [ "81", "A", "ALA",], [ "82", "A", "SER",], [ "83", "A", "PRO",], [ "84", "A", "PHE",], [ "86", "A", "LEU",], [ "98", "A", "PRO",], [ "123", "A", "THR",], [ "125", "A", "SER",], [ "126", "A", "TYR",], [ "127", "A", "ALA",], [ "167", "A", "TYR",], [ "168", "A", "ILE",], [ "171", "A", "LYS",], [ "196", "A", "PRO",], [ "198", "A", "TYR",], [ "199", "A", "VAL",], [ "215", "A", "GLU",], [ "216", "A", "THR",], [ "217", "A", "SER",],]

[RESULTS.FREQUENCY.KAA.RESIDUES]
ALA = 3
ARG = 1
GLU = 1
ILE = 2
LEU = 2
LYS = 2
PHE = 2
PRO = 3
SER = 3
THR = 5
TYR = 3
VAL = 3

[RESULTS.FREQUENCY.KAA.CLASS]
R1 = 13
R2 = 5
R3 = 8
R4 = 1
R5 = 3
RX = 0
