# pyKVFinder results

[FILES]
INPUT = "/mnt/bkup/peter_ccfour/Documents/KRED_Niklaus/000_final/000_homologic_2b_R_best/08_homolog_bindingsites_superposed/ORY92490_superposed_bindingsite_refined.pdb"
OUTPUT = "/mnt/bkup/peter_ccfour/Documents/KRED_Niklaus/000_final/000_homologic_2b_R_best/11_detected_cavities/ORY92490_cavities.pdb"

[PARAMETERS]
STEP = 0.6

[RESULTS.VOLUME]
KAA = 693.36

[RESULTS.AREA]
KAA = 512.0

[RESULTS.MAX_DEPTH]
KAA = 5.91

[RESULTS.AVG_DEPTH]
KAA = 2.1

[RESULTS.AVG_HYDROPATHY]
KAA = -0.37
EisenbergWeiss = [ -1.42, 2.6,]

[RESULTS.RESIDUES]
KAA = [ [ "12", "A", "THR",], [ "15", "A", "SER",], [ "17", "A", "PHE",], [ "18", "A", "VAL",], [ "36", "A", "VAL",], [ "38", "A", "ARG",], [ "62", "A", "VAL",], [ "65", "A", "PHE",], [ "71", "A", "PHE",], [ "84", "A", "ALA",], [ "85", "A", "ALA",], [ "86", "A", "THR",], [ "87", "A", "PRO",], [ "88", "A", "ILE",], [ "90", "A", "PHE",], [ "126", "A", "THR",], [ "128", "A", "SER",], [ "129", "A", "ILE",], [ "130", "A", "ALA",], [ "167", "A", "PHE",], [ "170", "A", "TYR",], [ "174", "A", "LYS",], [ "199", "A", "PRO",], [ "200", "A", "THR",], [ "201", "A", "LEU",], [ "202", "A", "VAL",], [ "208", "A", "GLN",], [ "219", "A", "VAL",], [ "220", "A", "SER",], [ "221", "A", "SER",], [ "224", "A", "TRP",], [ "238", "A", "ILE",],]

[RESULTS.FREQUENCY.KAA.RESIDUES]
ALA = 3
ARG = 1
GLN = 1
ILE = 3
LEU = 1
LYS = 1
PHE = 5
PRO = 2
SER = 4
THR = 4
TRP = 1
TYR = 1
VAL = 5

[RESULTS.FREQUENCY.KAA.CLASS]
R1 = 14
R2 = 7
R3 = 9
R4 = 0
R5 = 2
RX = 0
