# pyKVFinder results

[FILES]
INPUT = "/mnt/bkup/peter_ccfour/Documents/KRED_Niklaus/000_final/000_homologic/08_homolog_bindingsites_superposed/CCE40418_superposed_bindingsite_refined.pdb"
OUTPUT = "/mnt/bkup/peter_ccfour/Documents/KRED_Niklaus/000_final/000_homologic/11_detected_cavities/CCE40418_cavities.pdb"

[PARAMETERS]
STEP = 0.6

[RESULTS.VOLUME]
KAA = 492.7

[RESULTS.AREA]
KAA = 351.31

[RESULTS.MAX_DEPTH]
KAA = 4.2

[RESULTS.AVG_DEPTH]
KAA = 1.27

[RESULTS.AVG_HYDROPATHY]
KAA = -0.24
EisenbergWeiss = [ -1.42, 2.6,]

[RESULTS.RESIDUES]
KAA = [ [ "9", "A", "THR",], [ "11", "A", "PHE",], [ "12", "A", "ILE",], [ "13", "A", "ALA",], [ "31", "A", "VAL",], [ "32", "A", "ARG",], [ "61", "A", "ASP",], [ "62", "A", "ILE",], [ "84", "A", "THR",], [ "85", "A", "ALA",], [ "86", "A", "SER",], [ "87", "A", "PRO",], [ "88", "A", "VAL",], [ "90", "A", "PHE",], [ "102", "A", "PRO",], [ "127", "A", "THR",], [ "129", "A", "SER",], [ "167", "A", "TYR",], [ "171", "A", "LYS",], [ "196", "A", "PRO",], [ "198", "A", "VAL",], [ "199", "A", "VAL",], [ "214", "A", "ASN",], [ "215", "A", "TYR",], [ "216", "A", "SER",],]

[RESULTS.FREQUENCY.KAA.RESIDUES]
ALA = 2
ARG = 1
ASN = 1
ASP = 1
ILE = 2
LYS = 1
PHE = 2
PRO = 3
SER = 3
THR = 3
TYR = 2
VAL = 4

[RESULTS.FREQUENCY.KAA.CLASS]
R1 = 11
R2 = 4
R3 = 7
R4 = 1
R5 = 2
RX = 0
