# pyKVFinder results

[FILES]
INPUT = "/mnt/bkup/peter_ccfour/Documents/KRED_Niklaus/000_final/000_homologic/08_homolog_bindingsites_superposed/CCH60145_superposed_bindingsite_refined.pdb"
OUTPUT = "/mnt/bkup/peter_ccfour/Documents/KRED_Niklaus/000_final/000_homologic/11_detected_cavities/CCH60145_cavities.pdb"

[PARAMETERS]
STEP = 0.6

[RESULTS.VOLUME]
KAA = 128.09
KAB = 359.64

[RESULTS.AREA]
KAA = 109.08
KAB = 245.24

[RESULTS.MAX_DEPTH]
KAA = 2.4
KAB = 4.02

[RESULTS.AVG_DEPTH]
KAA = 0.72
KAB = 1.35

[RESULTS.AVG_HYDROPATHY]
KAA = 0.18
KAB = -0.37
EisenbergWeiss = [ -1.42, 2.6,]

[RESULTS.RESIDUES]
KAA = [ [ "9", "A", "THR",], [ "30", "A", "THR",], [ "32", "A", "ARG",], [ "54", "A", "VAL",], [ "56", "A", "ASP",], [ "57", "A", "ILE",], [ "81", "A", "ALA",], [ "83", "A", "PRO",], [ "98", "A", "PRO",],]
KAB = [ [ "11", "A", "TYR",], [ "12", "A", "ILE",], [ "13", "A", "ALA",], [ "80", "A", "THR",], [ "81", "A", "ALA",], [ "82", "A", "SER",], [ "84", "A", "VAL",], [ "124", "A", "THR",], [ "126", "A", "SER",], [ "164", "A", "TYR",], [ "168", "A", "LYS",], [ "197", "A", "PRO",], [ "199", "A", "TYR",], [ "200", "A", "VAL",], [ "215", "A", "ASN",], [ "216", "A", "PHE",], [ "217", "A", "SER",],]

[RESULTS.FREQUENCY.KAA.RESIDUES]
ALA = 1
ARG = 1
ASP = 1
ILE = 1
PRO = 2
THR = 2
VAL = 1

[RESULTS.FREQUENCY.KAA.CLASS]
R1 = 5
R2 = 0
R3 = 2
R4 = 1
R5 = 1
RX = 0

[RESULTS.FREQUENCY.KAB.RESIDUES]
ALA = 2
ASN = 1
ILE = 1
LYS = 1
PHE = 1
PRO = 1
SER = 3
THR = 2
TYR = 3
VAL = 2

[RESULTS.FREQUENCY.KAB.CLASS]
R1 = 6
R2 = 4
R3 = 6
R4 = 0
R5 = 1
RX = 0
