# pyKVFinder results

[FILES]
INPUT = "/mnt/bkup/peter_ccfour/Documents/KRED_Niklaus/000_final/000_homologic/08_homolog_bindingsites_superposed/EEQ37269_superposed_bindingsite_refined.pdb"
OUTPUT = "/mnt/bkup/peter_ccfour/Documents/KRED_Niklaus/000_final/000_homologic/11_detected_cavities/EEQ37269_cavities.pdb"

[PARAMETERS]
STEP = 0.6

[RESULTS.VOLUME]
KAA = 434.81

[RESULTS.AREA]
KAA = 313.66

[RESULTS.MAX_DEPTH]
KAA = 5.13

[RESULTS.AVG_DEPTH]
KAA = 1.51

[RESULTS.AVG_HYDROPATHY]
KAA = -0.03
EisenbergWeiss = [ -1.42, 2.6,]

[RESULTS.RESIDUES]
KAA = [ [ "10", "A", "ASN",], [ "12", "A", "TYR",], [ "13", "A", "ILE",], [ "31", "A", "SER",], [ "33", "A", "ARG",], [ "37", "A", "LYS",], [ "56", "A", "SER",], [ "57", "A", "PHE",], [ "58", "A", "VAL",], [ "79", "A", "SER",], [ "80", "A", "ALA",], [ "81", "A", "SER",], [ "82", "A", "PRO",], [ "83", "A", "VAL",], [ "122", "A", "THR",], [ "124", "A", "SER",], [ "158", "A", "TYR",], [ "162", "A", "LYS",], [ "187", "A", "PRO",], [ "189", "A", "TYR",], [ "190", "A", "VAL",], [ "207", "A", "SER",], [ "208", "A", "THR",],]

[RESULTS.FREQUENCY.KAA.RESIDUES]
ALA = 1
ARG = 1
ASN = 1
ILE = 1
LYS = 2
PHE = 1
PRO = 2
SER = 6
THR = 2
TYR = 3
VAL = 3

[RESULTS.FREQUENCY.KAA.CLASS]
R1 = 7
R2 = 4
R3 = 9
R4 = 0
R5 = 3
RX = 0
