# pyKVFinder results

[FILES]
INPUT = "/mnt/bkup/peter_ccfour/Documents/KRED_Niklaus/000_final/000_homologic/08_homolog_bindingsites_superposed/EGW31012_superposed_bindingsite_refined.pdb"
OUTPUT = "/mnt/bkup/peter_ccfour/Documents/KRED_Niklaus/000_final/000_homologic/11_detected_cavities/EGW31012_cavities.pdb"

[PARAMETERS]
STEP = 0.6

[RESULTS.VOLUME]
KAA = 105.62
KAB = 369.79

[RESULTS.AREA]
KAA = 99.25
KAB = 256.27

[RESULTS.MAX_DEPTH]
KAA = 2.47
KAB = 3.29

[RESULTS.AVG_DEPTH]
KAA = 0.75
KAB = 1.14

[RESULTS.AVG_HYDROPATHY]
KAA = 0.34
KAB = -0.48
EisenbergWeiss = [ -1.42, 2.6,]

[RESULTS.RESIDUES]
KAA = [ [ "12", "A", "ASN",], [ "33", "A", "SER",], [ "34", "A", "VAL",], [ "35", "A", "ARG",], [ "57", "A", "ILE",], [ "59", "A", "GLU",], [ "60", "A", "LEU",], [ "83", "A", "ALA",], [ "85", "A", "PRO",], [ "100", "A", "PRO",],]
KAB = [ [ "14", "A", "PHE",], [ "15", "A", "VAL",], [ "16", "A", "ALA",], [ "82", "A", "ILE",], [ "83", "A", "ALA",], [ "84", "A", "SER",], [ "86", "A", "VAL",], [ "88", "A", "PHE",], [ "125", "A", "THR",], [ "127", "A", "SER",], [ "128", "A", "VAL",], [ "129", "A", "VAL",], [ "165", "A", "TYR",], [ "166", "A", "PHE",], [ "169", "A", "LYS",], [ "194", "A", "PRO",], [ "196", "A", "TYR",], [ "197", "A", "VAL",], [ "212", "A", "ASN",], [ "213", "A", "LEU",], [ "214", "A", "SER",],]

[RESULTS.FREQUENCY.KAA.RESIDUES]
ALA = 1
ARG = 1
ASN = 1
GLU = 1
ILE = 1
LEU = 1
PRO = 2
SER = 1
VAL = 1

[RESULTS.FREQUENCY.KAA.CLASS]
R1 = 6
R2 = 0
R3 = 2
R4 = 1
R5 = 1
RX = 0

[RESULTS.FREQUENCY.KAB.RESIDUES]
ALA = 2
ASN = 1
ILE = 1
LEU = 1
LYS = 1
PHE = 3
PRO = 1
SER = 3
THR = 1
TYR = 2
VAL = 5

[RESULTS.FREQUENCY.KAB.CLASS]
R1 = 10
R2 = 5
R3 = 5
R4 = 0
R5 = 1
RX = 0
