# pyKVFinder results

[FILES]
INPUT = "/mnt/bkup/peter_ccfour/Documents/KRED_Niklaus/000_final/000_homologic/08_homolog_bindingsites_superposed/EGW32253_superposed_bindingsite_refined.pdb"
OUTPUT = "/mnt/bkup/peter_ccfour/Documents/KRED_Niklaus/000_final/000_homologic/11_detected_cavities/EGW32253_cavities.pdb"

[PARAMETERS]
STEP = 0.6

[RESULTS.VOLUME]
KAA = 129.82
KAB = 314.93

[RESULTS.AREA]
KAA = 108.9
KAB = 256.29

[RESULTS.MAX_DEPTH]
KAA = 2.24
KAB = 4.61

[RESULTS.AVG_DEPTH]
KAA = 0.69
KAB = 1.48

[RESULTS.AVG_HYDROPATHY]
KAA = 0.52
KAB = -0.49
EisenbergWeiss = [ -1.42, 2.6,]

[RESULTS.RESIDUES]
KAA = [ [ "12", "A", "ASN",], [ "33", "A", "SER",], [ "34", "A", "VAL",], [ "35", "A", "ARG",], [ "39", "A", "LYS",], [ "57", "A", "VAL",], [ "59", "A", "SER",], [ "60", "A", "LEU",], [ "61", "A", "THR",], [ "83", "A", "ALA",], [ "85", "A", "PRO",], [ "100", "A", "PRO",],]
KAB = [ [ "14", "A", "PHE",], [ "15", "A", "ILE",], [ "16", "A", "ALA",], [ "82", "A", "THR",], [ "83", "A", "ALA",], [ "84", "A", "SER",], [ "86", "A", "PHE",], [ "88", "A", "PHE",], [ "125", "A", "THR",], [ "127", "A", "SER",], [ "129", "A", "VAL",], [ "165", "A", "TYR",], [ "166", "A", "PHE",], [ "169", "A", "LYS",], [ "194", "A", "PRO",], [ "196", "A", "TYR",], [ "197", "A", "VAL",], [ "212", "A", "ASN",], [ "214", "A", "SER",],]

[RESULTS.FREQUENCY.KAA.RESIDUES]
ALA = 1
ARG = 1
ASN = 1
LEU = 1
LYS = 1
PRO = 2
SER = 2
THR = 1
VAL = 2

[RESULTS.FREQUENCY.KAA.CLASS]
R1 = 6
R2 = 0
R3 = 4
R4 = 0
R5 = 2
RX = 0

[RESULTS.FREQUENCY.KAB.RESIDUES]
ALA = 2
ASN = 1
ILE = 1
LYS = 1
PHE = 4
PRO = 1
SER = 3
THR = 2
TYR = 2
VAL = 2

[RESULTS.FREQUENCY.KAB.CLASS]
R1 = 6
R2 = 6
R3 = 6
R4 = 0
R5 = 1
RX = 0
