# pyKVFinder results

[FILES]
INPUT = "/mnt/bkup/peter_ccfour/Documents/KRED_Niklaus/000_final/000_homologic/08_homolog_bindingsites_superposed/EGW33854_superposed_bindingsite_refined.pdb"
OUTPUT = "/mnt/bkup/peter_ccfour/Documents/KRED_Niklaus/000_final/000_homologic/11_detected_cavities/EGW33854_cavities.pdb"

[PARAMETERS]
STEP = 0.6

[RESULTS.VOLUME]
KAA = 122.9
KAB = 377.57

[RESULTS.AREA]
KAA = 98.35
KAB = 257.6

[RESULTS.MAX_DEPTH]
KAA = 2.16
KAB = 4.02

[RESULTS.AVG_DEPTH]
KAA = 0.64
KAB = 1.38

[RESULTS.AVG_HYDROPATHY]
KAA = 0.31
KAB = -0.32
EisenbergWeiss = [ -1.42, 2.6,]

[RESULTS.RESIDUES]
KAA = [ [ "19", "A", "ASN",], [ "40", "A", "SER",], [ "41", "A", "VAL",], [ "42", "A", "ARG",], [ "64", "A", "ILE",], [ "66", "A", "THR",], [ "67", "A", "LEU",], [ "68", "A", "SER",], [ "90", "A", "ALA",], [ "92", "A", "PRO",], [ "107", "A", "PRO",],]
KAB = [ [ "21", "A", "TYR",], [ "22", "A", "ILE",], [ "23", "A", "ALA",], [ "89", "A", "THR",], [ "90", "A", "ALA",], [ "91", "A", "SER",], [ "93", "A", "VAL",], [ "95", "A", "PHE",], [ "132", "A", "THR",], [ "134", "A", "SER",], [ "136", "A", "VAL",], [ "172", "A", "TYR",], [ "176", "A", "LYS",], [ "201", "A", "PRO",], [ "203", "A", "TYR",], [ "204", "A", "THR",], [ "219", "A", "ASN",], [ "220", "A", "LEU",], [ "221", "A", "SER",],]

[RESULTS.FREQUENCY.KAA.RESIDUES]
ALA = 1
ARG = 1
ASN = 1
ILE = 1
LEU = 1
PRO = 2
SER = 2
THR = 1
VAL = 1

[RESULTS.FREQUENCY.KAA.CLASS]
R1 = 6
R2 = 0
R3 = 4
R4 = 0
R5 = 1
RX = 0

[RESULTS.FREQUENCY.KAB.RESIDUES]
ALA = 2
ASN = 1
ILE = 1
LEU = 1
LYS = 1
PHE = 1
PRO = 1
SER = 3
THR = 3
TYR = 3
VAL = 2

[RESULTS.FREQUENCY.KAB.CLASS]
R1 = 7
R2 = 4
R3 = 7
R4 = 0
R5 = 1
RX = 0
