# pyKVFinder results

[FILES]
INPUT = "/mnt/bkup/peter_ccfour/Documents/KRED_Niklaus/000_final/000_homologic/08_homolog_bindingsites_superposed/EGW35463_superposed_bindingsite_refined.pdb"
OUTPUT = "/mnt/bkup/peter_ccfour/Documents/KRED_Niklaus/000_final/000_homologic/11_detected_cavities/EGW35463_cavities.pdb"

[PARAMETERS]
STEP = 0.6

[RESULTS.VOLUME]
KAA = 502.2

[RESULTS.AREA]
KAA = 382.6

[RESULTS.MAX_DEPTH]
KAA = 5.13

[RESULTS.AVG_DEPTH]
KAA = 1.34

[RESULTS.AVG_HYDROPATHY]
KAA = -0.22
EisenbergWeiss = [ -1.42, 2.6,]

[RESULTS.RESIDUES]
KAA = [ [ "12", "A", "ASN",], [ "14", "A", "PHE",], [ "15", "A", "ILE",], [ "16", "A", "ALA",], [ "33", "A", "SER",], [ "35", "A", "ARG",], [ "39", "A", "LYS",], [ "57", "A", "VAL",], [ "59", "A", "SER",], [ "60", "A", "LEU",], [ "61", "A", "THR",], [ "82", "A", "ALA",], [ "83", "A", "ALA",], [ "84", "A", "SER",], [ "85", "A", "PRO",], [ "86", "A", "VAL",], [ "88", "A", "PHE",], [ "100", "A", "PRO",], [ "125", "A", "THR",], [ "127", "A", "SER",], [ "129", "A", "VAL",], [ "165", "A", "TYR",], [ "169", "A", "LYS",], [ "194", "A", "PRO",], [ "196", "A", "TYR",], [ "197", "A", "VAL",], [ "212", "A", "ASN",], [ "213", "A", "LEU",], [ "214", "A", "SER",],]

[RESULTS.FREQUENCY.KAA.RESIDUES]
ALA = 3
ARG = 1
ASN = 2
ILE = 1
LEU = 2
LYS = 2
PHE = 2
PRO = 3
SER = 5
THR = 2
TYR = 2
VAL = 4

[RESULTS.FREQUENCY.KAA.CLASS]
R1 = 13
R2 = 4
R3 = 9
R4 = 0
R5 = 3
RX = 0
