# pyKVFinder results

[FILES]
INPUT = "/mnt/bkup/peter_ccfour/Documents/KRED_Niklaus/000_final/000_homologic/08_homolog_bindingsites_superposed/EIW07406_superposed_bindingsite_refined.pdb"
OUTPUT = "/mnt/bkup/peter_ccfour/Documents/KRED_Niklaus/000_final/000_homologic/11_detected_cavities/EIW07406_cavities.pdb"

[PARAMETERS]
STEP = 0.6

[RESULTS.VOLUME]
KAA = 129.6
KAB = 315.36

[RESULTS.AREA]
KAA = 113.37
KAB = 248.11

[RESULTS.MAX_DEPTH]
KAA = 2.08
KAB = 4.87

[RESULTS.AVG_DEPTH]
KAA = 0.71
KAB = 1.82

[RESULTS.AVG_HYDROPATHY]
KAA = 0.31
KAB = -0.45
EisenbergWeiss = [ -1.42, 2.6,]

[RESULTS.RESIDUES]
KAA = [ [ "9", "A", "ASN",], [ "30", "A", "SER",], [ "32", "A", "ARG",], [ "36", "A", "LYS",], [ "55", "A", "VAL",], [ "57", "A", "ASP",], [ "58", "A", "ILE",], [ "59", "A", "SER",], [ "82", "A", "ALA",], [ "84", "A", "PRO",], [ "99", "A", "PRO",],]
KAB = [ [ "11", "A", "PHE",], [ "12", "A", "ILE",], [ "13", "A", "ALA",], [ "81", "A", "THR",], [ "82", "A", "ALA",], [ "83", "A", "SER",], [ "85", "A", "PHE",], [ "125", "A", "THR",], [ "127", "A", "SER",], [ "165", "A", "TYR",], [ "169", "A", "LYS",], [ "196", "A", "PRO",], [ "198", "A", "TYR",], [ "199", "A", "VAL",], [ "214", "A", "ASN",], [ "216", "A", "SER",],]

[RESULTS.FREQUENCY.KAA.RESIDUES]
ALA = 1
ARG = 1
ASN = 1
ASP = 1
ILE = 1
LYS = 1
PRO = 2
SER = 2
VAL = 1

[RESULTS.FREQUENCY.KAA.CLASS]
R1 = 5
R2 = 0
R3 = 3
R4 = 1
R5 = 2
RX = 0

[RESULTS.FREQUENCY.KAB.RESIDUES]
ALA = 2
ASN = 1
ILE = 1
LYS = 1
PHE = 2
PRO = 1
SER = 3
THR = 2
TYR = 2
VAL = 1

[RESULTS.FREQUENCY.KAB.CLASS]
R1 = 5
R2 = 4
R3 = 6
R4 = 0
R5 = 1
RX = 0
