# pyKVFinder results

[FILES]
INPUT = "/mnt/bkup/peter_ccfour/Documents/KRED_Niklaus/000_final/000_homologic/08_homolog_bindingsites_superposed/OIW25712_superposed_bindingsite_refined.pdb"
OUTPUT = "/mnt/bkup/peter_ccfour/Documents/KRED_Niklaus/000_final/000_homologic/11_detected_cavities/OIW25712_cavities.pdb"

[PARAMETERS]
STEP = 0.6

[RESULTS.VOLUME]
KAA = 840.89

[RESULTS.AREA]
KAA = 467.28

[RESULTS.MAX_DEPTH]
KAA = 8.53

[RESULTS.AVG_DEPTH]
KAA = 2.57

[RESULTS.AVG_HYDROPATHY]
KAA = 0.01
EisenbergWeiss = [ -1.42, 2.6,]

[RESULTS.RESIDUES]
KAA = [ [ "25", "A", "SER",], [ "27", "A", "PHE",], [ "28", "A", "ILE",], [ "29", "A", "ALA",], [ "47", "A", "VAL",], [ "48", "A", "ARG",], [ "52", "A", "LYS",], [ "75", "A", "ASP",], [ "76", "A", "ILE",], [ "77", "A", "THR",], [ "98", "A", "THR",], [ "99", "A", "ALA",], [ "100", "A", "SER",], [ "101", "A", "PRO",], [ "102", "A", "TYR",], [ "116", "A", "PRO",], [ "141", "A", "THR",], [ "143", "A", "SER",], [ "177", "A", "TYR",], [ "181", "A", "LYS",], [ "206", "A", "ASN",], [ "208", "A", "TYR",], [ "209", "A", "THR",], [ "214", "A", "GLN",], [ "224", "A", "ASN",], [ "225", "A", "ALA",], [ "226", "A", "SER",],]

[RESULTS.FREQUENCY.KAA.RESIDUES]
ALA = 3
ARG = 1
ASN = 2
ASP = 1
GLN = 1
ILE = 2
LYS = 2
PHE = 1
PRO = 2
SER = 4
THR = 4
TYR = 3
VAL = 1

[RESULTS.FREQUENCY.KAA.CLASS]
R1 = 8
R2 = 4
R3 = 11
R4 = 1
R5 = 3
RX = 0
