# pyKVFinder results

[FILES]
INPUT = "/mnt/bkup/peter_ccfour/Documents/KRED_Niklaus/000_final/000_homologic/08_homolog_bindingsites_superposed/ORY92490_superposed_bindingsite_refined.pdb"
OUTPUT = "/mnt/bkup/peter_ccfour/Documents/KRED_Niklaus/000_final/000_homologic/11_detected_cavities/ORY92490_cavities.pdb"

[PARAMETERS]
STEP = 0.6

[RESULTS.VOLUME]
KAA = 524.23

[RESULTS.AREA]
KAA = 388.12

[RESULTS.MAX_DEPTH]
KAA = 5.82

[RESULTS.AVG_DEPTH]
KAA = 1.83

[RESULTS.AVG_HYDROPATHY]
KAA = -0.43
EisenbergWeiss = [ -1.42, 2.6,]

[RESULTS.RESIDUES]
KAA = [ [ "15", "A", "SER",], [ "17", "A", "PHE",], [ "18", "A", "VAL",], [ "37", "A", "PHE",], [ "38", "A", "ARG",], [ "65", "A", "PHE",], [ "84", "A", "ALA",], [ "85", "A", "ALA",], [ "86", "A", "THR",], [ "87", "A", "PRO",], [ "88", "A", "ILE",], [ "90", "A", "PHE",], [ "126", "A", "THR",], [ "128", "A", "SER",], [ "130", "A", "ALA",], [ "170", "A", "TYR",], [ "174", "A", "LYS",], [ "199", "A", "PRO",], [ "201", "A", "LEU",], [ "202", "A", "VAL",], [ "208", "A", "GLN",], [ "219", "A", "VAL",], [ "220", "A", "SER",], [ "221", "A", "SER",],]

[RESULTS.FREQUENCY.KAA.RESIDUES]
ALA = 3
ARG = 1
GLN = 1
ILE = 1
LEU = 1
LYS = 1
PHE = 4
PRO = 2
SER = 4
THR = 2
TYR = 1
VAL = 3

[RESULTS.FREQUENCY.KAA.CLASS]
R1 = 10
R2 = 5
R3 = 7
R4 = 0
R5 = 2
RX = 0
