# pyKVFinder results

[FILES]
INPUT = "/mnt/bkup/peter_ccfour/Documents/KRED_Niklaus/000_final/000_homologic_2b_R_best/Ort-RDM-1_3_bindingsite.pdb"
OUTPUT = "/mnt/bkup/peter_ccfour/Documents/KRED_Niklaus/000_final/000_homologic_2b_R_best/reference_cavity_analysis/reference_cavities.pdb"

[PARAMETERS]
STEP = 0.6

[RESULTS.VOLUME]
KAA = 696.6

[RESULTS.AREA]
KAA = 483.47

[RESULTS.MAX_DEPTH]
KAA = 5.16

[RESULTS.AVG_DEPTH]
KAA = 1.93

[RESULTS.AVG_HYDROPATHY]
KAA = -0.16
EisenbergWeiss = [ -1.42, 2.6,]

[RESULTS.RESIDUES]
KAA = [ [ "13", "A", "THR",], [ "16", "A", "THR",], [ "18", "A", "TYR",], [ "19", "A", "ILE",], [ "37", "A", "THR",], [ "38", "A", "THR",], [ "39", "A", "ARG",], [ "43", "A", "LYS",], [ "65", "A", "ILE",], [ "67", "A", "ASP",], [ "68", "A", "VAL",], [ "87", "A", "VAL",], [ "88", "A", "ALA",], [ "89", "A", "SER",], [ "91", "A", "VAL",], [ "93", "A", "MET",], [ "127", "A", "THR",], [ "129", "A", "SER",], [ "130", "A", "SER",], [ "131", "A", "THR",], [ "168", "A", "PHE",], [ "171", "A", "TYR",], [ "175", "A", "LYS",], [ "200", "A", "PRO",], [ "201", "A", "ASP",], [ "202", "A", "SER",], [ "203", "A", "ASN",], [ "214", "A", "PRO",], [ "215", "A", "SER",], [ "216", "A", "THR",], [ "219", "A", "PHE",], [ "234", "A", "PHE",], [ "237", "A", "GLN",],]

[RESULTS.FREQUENCY.KAA.RESIDUES]
ALA = 1
ARG = 1
ASN = 1
ASP = 2
GLN = 1
ILE = 2
LYS = 2
MET = 1
PHE = 3
PRO = 2
SER = 5
THR = 7
TYR = 2
VAL = 3

[RESULTS.FREQUENCY.KAA.CLASS]
R1 = 8
R2 = 5
R3 = 15
R4 = 2
R5 = 3
RX = 0
